services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    command: ["node", "dist/main.js"]

  grafana:
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
