export const USER = {
  DUPLICATE: 'User already exists with this mobile number or email',
  NOT_FOUND: 'User not found',
  CREATED: 'User created successfully',
  UPDATED: 'User updated successfully',
  DEACTIVATED: 'User deactivated successfully',
  INVALID_CREDENTIALS: 'Invalid credentials',
  BLOCKED: 'Account is blocked',
  PROFILE_NOT_FOUND: 'Associated profile not found',
  SESSION_EXPIRED: 'Session has expired',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  LOGOUT: 'User logged out successfully',
  EXPIRED_IN: '15m',
  EXPIRED_IN_MILLISECONDS: 15 * 60 * 1000,
  TOKEN_REFRESHED: 'Token refreshed successfully',
  DELETED: 'User deleted successfully',
  AGENT_MISSED: 'Invalid or missing x-agent header',
  LOGIN: 'User logged in successfully',
};
