/**
 * User Activity Tracker Collection
 * --------------------------------
 * Purpose : Track user activities (task/session based)
 * Used by : APP / ADMIN / REPORTING
 *
 * Contains:
 * - User identity
 * - Activity name & classification
 * - Status tracking (enum)
 * - Start & end time
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { ActivityStatus } from 'src/shared/enums/activity.enums';

export type ActivityDocument = HydratedDocument<Activity>;

@Schema({ timestamps: true})
export class Activity {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  // Unique activity reference ID
  @AutoGenerated()
  @Prop({ required: true, unique: true })
  activityId: String;

  // User who performed the activity
  @Prop({ required: true })
  workSessionId: String;

  // User who performed the activity
  @Prop({ required: true })
  userId: String;

  // User name (for quick reference)
  @Prop()
  userName: String;

  // User who performed the activity
  @Prop({ required: true })
  vanId: String;

  // User name (for quick reference)
  @Prop()
  vanName: String;

  /* ======================================================
   * ACTIVITY DETAILS
   * ====================================================== */

  // Activity name (e.g., "Meeting", "Development", "Break")
  @Prop({ required: true, trim: true })
  name: String;

  // Description of activity
  @Prop({ trim: true })
  description: String;

  // Activity status
  @Prop({
    type: String,
    enum: ActivityStatus,
    default: ActivityStatus.ACTIVE,
  })
  status: ActivityStatus;

  // Category (e.g., WORK, PERSONAL)
  @Prop({ trim: true })
  category: String;

  // Sub-category (e.g., CODING, TESTING)
  @Prop({ trim: true })
  subCategory: String;

  /* ======================================================
   * TIME TRACKING
   * ====================================================== */

  // Activity start time
  @Prop({ required: true })
  startTime: Date;

  // Activity end times
  @Prop()
  endTime: Date;
}

export const ActivitySchema = SchemaFactory.createForClass(Activity);
