/**
 * Beat Collection
 * ---------------
 * Purpose : Beat master classification
 * Used by : BACK_OFFICE / ADMIN / LOCATION SETUP
 *
 * Contains:
 * - Beat identity
 * - Beat name
 * - Beat status
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { BeatStatus } from 'src/shared/enums/beat.enums';

export type BeatDocument = HydratedDocument<Beat>;

@Schema({ timestamps: true, collection: 'beat_master' })
export class Beat {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  // Reference of beat
  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  beatId: string;

  // Display name of beat
  @Prop({ required: true, unique: true, trim: true, type: String })
  name: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  // Beat availability status
  @Prop({
    type: String,
    enum: BeatStatus,
    default: BeatStatus.ACTIVE,
  })
  status: BeatStatus;
}

export const BeatSchema = SchemaFactory.createForClass(Beat);
