/**
 * Channels Collection
 * -------------------
 * Purpose : Channel master classification
 * Used by : BACK_OFFICE / ADMIN / LOCATION SETUP
 *
 * Contains:
 * - Channel identity
 * - Channel name
 * - Channel status
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { ChannelStatus } from 'src/shared/enums/channel.enums';

export type ChannelDocument = HydratedDocument<Channel>;

@Schema({ timestamps: true, collection: 'channel_master' })
export class Channel {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  // Reference of channel
  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  channelId: string;

  // Display name of channel
  @Prop({ required: true, unique: true, trim: true, type: String})
  name: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  // Channel availability status
  @Prop({
    type: String,
    enum: ChannelStatus,
    default: ChannelStatus.ACTIVE,
  })
  status: ChannelStatus;
}

export const ChannelSchema = SchemaFactory.createForClass(Channel);
