/**
 * Countries Collection
 * -------------------
 * Purpose : Country master classification
 * Used by : BACK_OFFICE / ADMIN / LOCATION SETUP
 *
 * Contains:
 * - Country identity
 * - Country name
 * - Country status
 *
 * Notes:
 * - Countries are used for address and location mapping
 * - Soft deletes preserve audit history
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { CountryStatus } from 'src/shared/enums/country.enums';



export type CountryDocument = HydratedDocument<Country>;

@Schema({ timestamps: true, collection: 'country_master' })
export class Country {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  // Reference of country
  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  countryId: string;

  // Display name of country
  @Prop({ required: true, unique: true, trim: true, type: String})
  name: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  // Country availability status
  @Prop({
    type: String,
    enum: CountryStatus,
    default: CountryStatus.ACTIVE,
  })
  status: CountryStatus;
}

export const CountrySchema = SchemaFactory.createForClass(Country);