/**
 * Customer Collection
 * -------------------
 * Purpose : Customer master classification
 * Used by : BACK_OFFICE / ADMIN / SALES / ROUTE PLANNING
 *
 * Contains:
 * - Customer identity
 * - Category reference
 * - Channel reference
 * - Outlet type reference
 * - Market reference
 * - Province reference
 * - Geo location
 * - Status
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { CustomerStatus } from 'src/shared/enums/customer.enums';

export type CustomerDocument = HydratedDocument<Customer>;

/* ======================================================
 * GEO TAG SUB SCHEMA
 * ====================================================== */

@Schema({ _id: false })
export class GeoTag {
  // Latitude (-90 to +90)
  @Prop({
    required: true,
    min: -90,
    max: 90,
  })
  lat: number;

  // Longitude (-180 to +180)
  @Prop({
    required: true,
    min: -180,
    max: 180,
  })
  lng: number;
}

export const GeoTagSchema = SchemaFactory.createForClass(GeoTag);

/* ======================================================
 * CUSTOMER SCHEMA
 * ====================================================== */

@Schema({ timestamps: true, collection: 'customer_master' })
export class Customer {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  customerId: string;

  /* ======================================================
   * CLASSIFICATION (REFERENCES)
   * ====================================================== */

  // Reference of customer category
  @Prop({
    required: true,
    ref: 'customer_category_master',
    index: true,
    type: String,
  })
  customerCategoryId: string;

  // Reference of channel
  @Prop({ required: true, ref: 'channel_master', index: true, type: String })
  channelId: string;

  // Reference of outlet type
  @Prop({
    required: true,
    ref: 'outlet_type_master',
    index: true,
    type: String,
  })
  customerTypeId: string;

  // Reference of market
  @Prop({ required: true, ref: 'market_master', index: true, type: String })
  marketId: string;

  // Reference of province/state
  @Prop({ required: true, ref: 'province_master', index: true, type: String })
  provinceId: string;

  /* ======================================================
   * BASIC DETAILS
   * ====================================================== */

  @Prop({ required: true, trim: true, type: String })
  ownerName: string;

  @Prop({
    required: true,
    trim: true,
    index: true,
    type: String,
  })
  phoneNumber: string;

  @Prop({ required: true, trim: true, type: String })
  name: string;

  @Prop({ required: true, type: String })
  segmentation: string;

  @Prop({
    type: {
      line1: {
        type: String,
        required: true,
        trim: true,
        minlength: 3,
        maxlength: 150,
      },
      line2: { type: String, trim: true, maxlength: 150 },
    },
    required: true,
  })
  address: {
    line1: string;
    line2?: string;
  };

  @Prop({ type: Number })
  creditLimit: number;

  @Prop({ type: Number })
  outstanding: number;
  /* ======================================================
   * LOCATION
   * ====================================================== */

  @Prop({
    type: GeoTagSchema,
    required: false,
    default: null,
  })
  geoTag?: GeoTag;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: CustomerStatus,
    default: CustomerStatus.ACTIVE,
    index: true,
  })
  status: CustomerStatus;

  @Prop({
    type: Date,
  })
  lastVisitedAt: Date;
}

export const CustomerSchema = SchemaFactory.createForClass(Customer);
