/**
 * Customer Categories Collection
 * ------------------------------
 * Purpose : Customer classification and grouping
 * Used by : BACK_OFFICE / ADMIN / SALES
 *
 * Contains:
 * - Category identity
 * - Category name
 * - Category status
 *
 * Notes:
 * - Customer categories are used for segmentation and reporting
 * - Soft deletes preserve audit history
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { CustomerCategoryStatus } from 'src/shared/enums/customer-category.enums';

export type CustomerCategoryDocument = HydratedDocument<CustomerCategory>;

@Schema({ collection: 'customer_category_master', timestamps: true })
export class CustomerCategory {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  // Unique business identifier for customer category
  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  customerCategoryId: string;

  // Display name of customer category
  @Prop({ required: true, unique: true, type: String })
  name: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  // Customer category availability status
  @Prop({
    type: String,
    enum: CustomerCategoryStatus,
    default: CustomerCategoryStatus.ACTIVE,
  })
  status: CustomerCategoryStatus;
}

export const CustomerCategorySchema =
  SchemaFactory.createForClass(CustomerCategory);
