/**
 * Customer Collection
 * -------------------
 * Purpose : Customer master classification
 * Used by : BACK_OFFICE / ADMIN / SALES / ROUTE PLANNING
 *
 * Contains:
 * - Customer identity
 * - Category reference
 * - Channel reference
 * - Outlet type reference
 * - Market reference
 * - Province reference
 * - Geo location
 * - Status
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { CustomerStatus } from 'src/shared/enums/customer.enums';

export type CustomerDocument = HydratedDocument<Customer>;

/* ======================================================
 * GEO TAG SUB SCHEMA
 * ====================================================== */

@Schema({ _id: false })
export class GeoTag {
  // Latitude (-90 to +90)
  @Prop({
    required: true,
    min: -90,
    max: 90,
  })
  lat: number;

  // Longitude (-180 to +180)
  @Prop({
    required: true,
    min: -180,
    max: 180,
  })
  lng: number;
}

export const GeoTagSchema = SchemaFactory.createForClass(GeoTag);

/* ======================================================
 * CUSTOMER SCHEMA
 * ====================================================== */

@Schema({ timestamps: true, collection: 'customer_master' })
export class Customer {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true })
  customerId: string;

  /* ======================================================
   * CLASSIFICATION (REFERENCES)
   * ====================================================== */

  // Reference of customer category
  @Prop({ required: true, ref: 'customer_category_master', index: true })
  customerCategoryId: string;

  // Reference of channel
  @Prop({ required: true, ref: 'channel_master', index: true })
  channelId: string;

  // Reference of outlet type
  @Prop({ required: true, ref: 'outlet_type_master', index: true })
  outletTypeId: string;

  // Reference of market
  @Prop({ required: true, ref: 'market_master', index: true })
  marketId: string;

  // Reference of province/state
  @Prop({ required: true, ref: 'province_master', index: true })
  provinceId: string;

  /* ======================================================
   * BASIC DETAILS
   * ====================================================== */

  @Prop({ required: true, trim: true })
  ownerName: string;

  @Prop({
    required: true,
    trim: true,
    index: true,
  })
  phoneNumber: string;

  @Prop({ required: true, trim: true })
  outletName: string;

  @Prop({ required: true })
  segmentation: string;

  @Prop({ required: true })
  address: string;

  /* ======================================================
   * LOCATION
   * ====================================================== */

  @Prop({
    type: GeoTagSchema,
    required: false,
    default: null,
  })
  geoTag?: GeoTag;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: CustomerStatus,
    default: CustomerStatus.ACTIVE,
    index: true,
  })
  status: CustomerStatus;
}

export const CustomerSchema = SchemaFactory.createForClass(Customer);
