/**
 * Customer Sales Collection (Header)
 * ---------------------------------
 * Purpose : Store van-wise customer sales transactions
 * Used by : SALES / BACK_OFFICE / ERP
 *
 * On CONFIRMED:
 *  - Deduct van_inventory
 *  - Insert inventory_transactions (SALE / OUT)
 *
 * Contains:
 * - Sale identity
 * - Van / customer / employee reference
 * - Sales date
 * - Total sales (qty / weight / value)
 * - Workflow status
 *
 * Notes:
 * - Line items stored in customer_sales_items
 * - All identifiers are stored as String (no ObjectId)
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { CustomerSalesStatus } from 'src/shared/enums/customer-sales.enums';

export type CustomerSalesDocument = HydratedDocument<CustomerSales>;

@Schema({ collection: 'customer_sales' })
export class CustomerSales {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  // Unique business identifier for sale
  @AutoGenerated()
  @Prop({ type: String, required: true, unique: true, index: true })
  salesId: string;

  /* ======================================================
   * REFERENCES
   * ====================================================== */

  // Van reference (vans.vanId)
  @Prop({ type: String, required: true, index: true })
  vanId: string;

  // Customer reference (customers.customerId)
  @Prop({ type: String, required: true, index: true })
  customerId: string;

  @Prop({ type: String, required: true, index: true })
  customerName: string;

  // Employee reference (employees.employeeId)
  @Prop({ type: String, required: true, index: true })
  employeeId: string;

  // Business date of sale (UTC)
  @Prop({ type: Date, required: true, index: true })
  date: Date;

  /* ======================================================
   * TOTALS (Derived from customer_sales_items)
   * ====================================================== */

  // Sum of sold quantities
  @Prop({ type: Number, default: 0 })
  totalQuantity: number;

  // Sum of sold weight
  @Prop({ type: Number, default: 0 })
  totalWeight: number;

  // Sum of sold value
  @Prop({ type: Number, default: 0 })
  totalValue: number;

  // Sum of sold value
  @Prop({ type: Number, default: 0 })
  totalReturnQuantity: number;

  /* ======================================================
   * META
   * ====================================================== */

  // Optional remark
  @Prop()
  remark?: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: CustomerSalesStatus,
    default: CustomerSalesStatus.DRAFT,
    index: true,
  })
  status: CustomerSalesStatus;
}

export const CustomerSalesSchema = SchemaFactory.createForClass(CustomerSales);

/**
 * Index for daily van-customer sales
 */
CustomerSalesSchema.index(
  { vanId: 1, customerId: 1, salesDate: 1 },
  { name: 'idx_customer_sales_daily' },
);
