/**
 * Daily Inventory Collection
 * -------------------------
 * Purpose : Store opening & closing stock per van per day
 * Used by : BACK_OFFICE / ADMIN / SALES
 *
 * Contains:
 * - Date reference
 * - Van reference
 * - Product reference
 * - Opening stock
 * - Inbound quantity
 * - Outbound quantity
 * - Adjustment quantity
 * - Closing stock
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { DailyInventoryStatus } from 'src/shared/enums/daily-inventory.enums';

export type DailyInventoryDocument = HydratedDocument<DailyInventory>;

@Schema({ collection: 'daily_inventories' })
export class DailyInventory {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  dailyInventoryId: string;

  /* ======================================================
   * DATE
   * ====================================================== */

  @Prop({ required: true, index: true, type: Date })
  date: Date; // ISO Date format with UTC

  /* ======================================================
   * VAN, EMPLOYEE & PRODUCT REFERENCES
   * ====================================================== */

  @Prop({ required: true, index: true, type: String })
  employeeId: string;

  @Prop({ required: true, index: true, type: String })
  vanId: string;

  @Prop({ required: true, index: true, type: String })
  productId: string;

  /* ======================================================
   * STOCK SNAPSHOT
   * ====================================================== */

  @Prop({
    type: Number,
    required: true,
    default: 0,
    min: 0,
  })
  openingQty: number;

  @Prop({
    type: Number,
    required: true,
    default: 0,
    min: 0,
  })
  inQty: number;

  @Prop({
    type: Number,
    required: true,
    default: 0,
    min: 0,
  })
  outQty: number;

  @Prop({
    type: Number,
    required: true,
    default: 0,
    min: 0,
  })
  adjustmentQty: number;

  @Prop({
    type: Number,
    required: true,
    default: 0,
    min: 0,
  })
  closingQty: number;

  /* ======================================================
   * META
   * ====================================================== */

  @Prop()
  remark?: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: DailyInventoryStatus,
    default: DailyInventoryStatus.DRAFT,
    index: true,
  })
  status: DailyInventoryStatus;
}

export const DailyInventorySchema =
  SchemaFactory.createForClass(DailyInventory);

// Compound unique index for date + vanId + productId
DailyInventorySchema.index(
  { date: 1, vanId: 1, productId: 1 },
  { unique: true, name: 'unique_daily_inventory' },
);
