/**
 * Designations Collection
 * -----------------------
 * Purpose : Employee designation and territory assignment master
 * Used by : BACK_OFFICE / ADMIN
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { DesignationStatus } from 'src/shared/enums/designation.enums';

export type DesignationDocument = HydratedDocument<Designation>;

@Schema({ timestamps: true, collection: 'designation_master' })
export class Designation {
  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  designationId!: string;

  @Prop({ required: true, unique: true, trim: true, type: String })
  name!: string;

  @Prop({ ref: 'ProductCategory', index: true, type: [String] })
  parentCategoryId?: string[];

  @Prop({ required: true, ref: 'country_master', index: true, type: String })
  countryId!: string;

  @Prop({ required: true, ref: 'province_master', index: true, type: String })
  provinceId!: string;

  @Prop({ required: true, ref: 'market_master', index: true, type: String })
  marketId!: string;

  @Prop({
    type: String,
    enum: DesignationStatus,
    default: DesignationStatus.ACTIVE,
  })
  status!: DesignationStatus;
}

export const DesignationSchema = SchemaFactory.createForClass(Designation);
