import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import {
  Direction,
  InventoryTransactionStatus,
  TransactionType,
} from 'src/shared/enums/inventory-transaction.enums';

export type InventoryTransactionDocument =
  HydratedDocument<InventoryTransaction>;

@Schema({
  timestamps: true,
  collection: 'inventory_transactions',
})
export class InventoryTransaction {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  transactionId: string;

  /* ======================================================
   * REFERENCES
   * ====================================================== */

  @Prop({ required: true, index: true, type: String })
  productId: string;

  @Prop({ required: true, index: true, type: String })
  vanId: string;

  @Prop({ required: true, index: true, type: String })
  employeeId: string;

  @Prop({ type: String, index: true })
  warehouseId?: string;

  /* ======================================================
   * TRANSACTION DETAILS
   * ====================================================== */

  @Prop({
    required: true,
    enum: TransactionType
    index: true,
  })
  transactionType: TransactionType; // LOAD | SALE | RETURN | DAMAGE | SETTLEMENT

  @Prop({
    required: true,
    enum:Direction,
    index: true,
  })
  direction: Direction; // IN | OUT

  @Prop({
    type: Number,
    required: true,
    min: 0.0001,
  })
  quantity: number;

  // Optional: useful for POS (cases + pieces breakdown)
  @Prop({ type: Number, default: 0 })
  cases?: number;

  @Prop({ type: Number, default: 0 })
  pieces?: number;

  /* ======================================================
   * BUSINESS META
   * ====================================================== */

  @Prop({ type: String, index: true })
  referenceNo?: string; // invoiceNo / loadNo / returnNo

  @Prop({ type: String })
  remark?: string;

  @Prop({
    type: Date,
    default: Date.now,
    index: true,
  })
  transactionDate: Date; // IMPORTANT for MIS

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: InventoryTransactionStatus,
    default: InventoryTransactionStatus.POSTED,
    index: true,
  })
  status: InventoryTransactionStatus;
}

export const InventoryTransactionSchema =
  SchemaFactory.createForClass(InventoryTransaction);

/* ======================================================
 * INDEXES (VERY IMPORTANT FOR MIS DASHBOARD 🚀)
 * ====================================================== */

// Fast filtering for reports
InventoryTransactionSchema.index({
  productId: 1,
  vanId: 1,
  transactionDate: -1,
});

// Dashboard queries
InventoryTransactionSchema.index({
  transactionType: 1,
  direction: 1,
  transactionDate: -1,
});

// Reference lookup
InventoryTransactionSchema.index({
  referenceNo: 1,
});
