/**
 * Inventory Transactions Collection
 * ---------------------------------
 * Purpose : Track every stock movement
 * Used by : BACK_OFFICE / ADMIN / SALES
 *
 * Contains:
 * - Transaction identity
 * - Product reference
 * - Van reference
 * - Transaction type
 * - Direction
 * - Quantity
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import {
  Direction,
  InventoryTransactionStatus,
  TransactionType,
} from 'src/shared/enums/inventory-transaction.enums';

export type InventoryTransactionDocument =
  HydratedDocument<InventoryTransaction>;

@Schema({ timestamps: true, collection: 'inventory_transactions' })
export class InventoryTransaction {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true })
  transactionId: string;

  /* ======================================================
   * PRODUCT REFERENCE
   * ====================================================== */

  @Prop({ required: true, index: true })
  productId: string;

  /* ======================================================
   * VAN REFERENCE
   * ====================================================== */

  @Prop({ required: true, index: true })
  vanId: string;

  /* ======================================================
   * Employee REFERENCE
   * ====================================================== */

  @Prop({ required: true, index: true })
  employeeId: string;

  /* ======================================================
   * OPTIONAL WAREHOUSE (LOADING)
   * ====================================================== */

  @Prop()
  warehouseId?: string;

  /* ======================================================
   * TRANSACTION DETAILS
   * ====================================================== */

  @Prop({ required: true, enum: TransactionType })
  transactionType: string;
  // LOAD | SALE | RETURN | DAMAGE | SETTLEMENT

  @Prop({ required: true, enum: Direction })
  direction: Direction;
  // IN | OUT

  @Prop({ type: Number, required: true, min: 0.0001 })
  quantity: number;

  /* ======================================================
   * META
   * ====================================================== */

  @Prop({
    type: String,
    required: true,
  })
  referenceNo?: string;

  @Prop()
  remark?: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: InventoryTransactionStatus,
    default: InventoryTransactionStatus.POSTED,
    index: true,
  })
  status: InventoryTransactionStatus;
}

export const InventoryTransactionSchema =
  SchemaFactory.createForClass(InventoryTransaction);
