/**
 * User Leave Tracker Collection
 * --------------------------------
 * Purpose : Track user activities (task/session based)
 * Used by : APP / ADMIN / REPORTING
 *
 * Contains:
 * - User identity
 * - Leave name & classification
 * - Status tracking (enum)
 * - Start & end time
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { LeaveStatus } from 'src/shared/enums/leave.enums';

export type LeaveDocument = HydratedDocument<Leave>;

@Schema({ timestamps: true })
export class Leave {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  // Unique Leave reference ID
  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  leaveId!: string;

  // User who performed the Leave
  @Prop({ required: true, type: String })
  userId!: string;

  // User name (for quick reference)
  @Prop({ type: String })
  userName!: string;

  // Description of Leave
  @Prop({ trim: true, type: String })
  type!: string;

  // Leave status
  @Prop({
    type: String,
    enum: LeaveStatus,
    default: LeaveStatus.COMPLETED,
  })
  status!: LeaveStatus;
}

export const LeaveSchema = SchemaFactory.createForClass(Leave);
