/**
 * NON-SALE COLLECTION
 * -------------------
 * Purpose : Capture visit where no sale/order is created
 * Used by : SALES / ROUTE EXECUTION / ANALYTICS
 *
 * NOTE:
 * - Linked with ShopVisit (single source of truth for visit)
 * - No geoTag / image (handled separately)
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { NonSaleStatus } from 'src/shared/enums/non-sale.enums';

export type NonSaleDocument = HydratedDocument<NonSale>;

@Schema({ timestamps: true, collection: 'non_sale' })
export class NonSale {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  nonSaleId: string;

  /* ======================================================
   * RELATIONSHIP (IMPORTANT)
   * ====================================================== */

  // 🔗 Link with ShopVisit (single source of truth)
  @Prop({ required: true, ref: 'shop_visits', index: true, type: String })
  visitId: string;

  // Outlet / Customer
  @Prop({ required: true, ref: 'customer_master', index: true, type: String })
  outletId: string;

  // Salesman / User
  @Prop({ required: true, ref: 'user_master', index: true, type: String })
  employeeId: string;

  // Salesman / User
  @Prop({ required: true, ref: 'user_master', index: true, type: String })
  vanId: string;

  /* ======================================================
   * NON-SALE DETAILS
   * ====================================================== */

  @Prop({
    required: true,
    index: true,
    type: String,
  })
  reasonCategoryId: string;

  @Prop({
    required: true,
    index: true,
    type: String,
  })
  reasonId: string;

  @Prop({
    trim: true,
    maxlength: 500,
    type: String,
  })
  remark: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: NonSaleStatus,
    default: NonSaleStatus.COMPLETED,
    index: true,
  })
  status: string;
}

export const NonSaleSchema = SchemaFactory.createForClass(NonSale);

/* ======================================================
 * INDEXES
 * ====================================================== */

// Ensure 1 non-sale per visit
NonSaleSchema.index({ visitId: 1 }, { unique: true });

// Query optimization
NonSaleSchema.index({ routeId: 1, userId: 1 });
