import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { OutletVerificationStatus } from 'src/shared/enums/outlet-verification.enums';

export type OutletVerificationDocument = HydratedDocument<OutletVerification>;

@Schema({ timestamps: true, collection: 'outlet_verifications' })
export class OutletVerification {
  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  outletVerificationId!: string;

  @Prop({ required: true, index: true, type: String })
  customerId!: string;

  @Prop({ required: true, index: true, type: String })
  requestedByEmployeeId!: string;

  @Prop({ type: String })
  requestedByEmployeeName?: string;

  @Prop({ type: String, index: true })
  assignedReviewerId?: string;

  @Prop({ type: String })
  reviewedByEmployeeId?: string;

  @Prop({ type: Date })
  reviewedAt?: Date;

  @Prop({ type: String, maxlength: 500 })
  reason?: string;

  @Prop({
    required: true,
    type: String,
    enum: OutletVerificationStatus,
    default: OutletVerificationStatus.PENDING,
    index: true,
  })
  status!: OutletVerificationStatus;
}

export const OutletVerificationSchema =
  SchemaFactory.createForClass(OutletVerification);

OutletVerificationSchema.index({ customerId: 1, createdAt: -1 });
OutletVerificationSchema.index(
  { customerId: 1, status: 1 },
  {
    unique: true,
    partialFilterExpression: {
      status: OutletVerificationStatus.PENDING,
      isDeleted: false,
    },
  },
);
