/**
 * Outlet Type Collection
 * -----------------------
 * Purpose : Outlet type master classification
 * Used by : BACK_OFFICE / ADMIN / LOCATION SETUP
 *
 * Contains:
 * - Outlet type identity
 * - Outlet type name
 * - Outlet type status
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { OutletTypeStatus } from 'src/shared/enums/outlet-type.enums';

export type OutletTypeDocument = HydratedDocument<OutletType>;

@Schema({ timestamps: true, collection: 'outlet_type_master' })
export class OutletType {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  // Reference of outlet type
  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  outletTypeId: string;

  // Display name of outlet type
  @Prop({ required: true, unique: true, trim: true, type: String })
  name: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  // Outlet type availability status
  @Prop({
    type: String,
    enum: OutletTypeStatus,
    default: OutletTypeStatus.ACTIVE,
  })
  status: OutletTypeStatus;
}

export const OutletTypeSchema = SchemaFactory.createForClass(OutletType);
