/**
 * Customer Payment Collection
 * ---------------------------
 * Purpose : Track payments collected from customers
 *
 * Supports:
 * - Full / Partial payments
 * - Multiple payment modes
 * - Linking with sales
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { PaymentMode, PaymentStatus } from 'src/shared/enums/payment.enums';


export type PaymentDocument = HydratedDocument<Payment>;

@Schema({ collection: 'customer_payments', timestamps: true })
export class Payment {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ type: String, required: true, unique: true, index: true })
  paymentId: string;

  /* ======================================================
   * REFERENCES
   * ====================================================== */

  @Prop({ type: String, required: true, index: true })
  customerId: string;

  @Prop({ type: String, required: true, index: true })
  vanId: string;

  @Prop({ type: String, required: true, index: true })
  employeeId: string;

  /* ======================================================
   * PAYMENT DETAILS
   * ====================================================== */

  // Total amount collected
  @Prop({ type: Number, required: true })
  amount: number;

  // Payment mode
  @Prop({
    type: String,
    enum: PaymentMode,
    required: true,
    index: true,
  })
  paymentMode: PaymentMode;

  // Payment status
  @Prop({
    type: String,
    enum: PaymentStatus,
    default: PaymentStatus.SUCCESS,
    index: true,
  })
  status: PaymentStatus;

  // Payment date
  @Prop({ type: Date, required: true, index: true })
  date: Date;

  /* ======================================================
   * LINKED SALES (IMPORTANT)
   * ====================================================== */

  // List of sales this payment is applied to
  @Prop({
    type: [
      {
        saleId: { type: String, required: true },
        amount: { type: Number, required: true },
      },
    ],
    default: [],
  })
  sales: {
    saleId: string;
    amount: number;
  }[];

  /* ======================================================
   * META
   * ====================================================== */

  @Prop()
  referenceNo?: string; // cheque no / txn id

  @Prop()
  remark?: string;
}

export const PaymentSchema = SchemaFactory.createForClass(Payment);

/* ======================================================
 * INDEXES
 * ====================================================== */

// Fast lookup per customer
PaymentSchema.index(
  { customerId: 1, date: -1 },
  { name: 'idx_customer_payment_date' },
);
