/**
 * Positions Collection
 * -----------------------
 * Purpose : Employee position and territory assignment master
 * Used by : BACK_OFFICE / ADMIN
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { PositionStatus } from 'src/shared/enums/position.enums';

export type PositionDocument = HydratedDocument<Position>;

@Schema({ timestamps: true, collection: 'position_master' })
export class Position {
  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  positionId!: string;

  @Prop({ required: true, unique: true, trim: true, type: String })
  name!: string;

  @Prop({ ref: 'ProductCategory', index: true, type: [String] })
  parentCategoryId?: string[];

  @Prop({ required: true, ref: 'country_master', index: true, type: String })
  countryId!: string;

  @Prop({ required: false, ref: 'province_master', index: true, type: String })
  provinceId?: string;

  @Prop({ required: false, ref: 'market_master', index: true, type: String })
  marketId?: string;

  /** Application role granted to the employee assigned to this position. */
  @Prop({ required: true, ref: 'Role', index: true, type: String })
  roleId!: string;

  /** Employee assigned to this position. */
  @Prop({
    required: false,
    ref: 'Employee',
    type: String,
  })
  employeeId?: string;

  /** Parent position in the reporting hierarchy. */
  @Prop({ required: false, ref: 'Position', index: true, type: String })
  reportTo?: string;

  /** One-based depth from the root position. */
  @Prop({ type: Number, required: true, min: 1, default: 1, index: true })
  hierarchyDepth!: number;

  /** Ancestor position IDs ordered from the root to the direct parent. */
  @Prop({ type: [String], default: [] })
  hierarchyPath!: string[];

  /** Vans available to employees assigned to this position. */
  @Prop({ type: [String], ref: 'Van', default: [] })
  vanIds!: string[];

  /** Allows the employee mapped to this position to work offline. */
  @Prop({ type: Boolean, default: false, index: true })
  offlineAccessAllowed!: boolean;

  @Prop({
    type: String,
    enum: PositionStatus,
    default: PositionStatus.ACTIVE,
  })
  status!: PositionStatus;
}

export const PositionSchema = SchemaFactory.createForClass(Position);

PositionSchema.index({ employeeId: 1 }, { unique: true, sparse: true });
PositionSchema.index({ hierarchyPath: 1 });
PositionSchema.index({ reportTo: 1, status: 1, isDeleted: 1 });
