/**
 * Price Master Collection
 * -----------------------
 * Purpose : Product price master
 * Used by : BACK_OFFICE / ADMIN / SALES
 *
 * Contains:
 * - Price identity
 * - Product price details
 * - Category details
 * - VAT inclusive / exclusive prices
 * - Effective date
 * - Price flag
 *
 * Notes:
 * - Product-wise pricing is stored here
 * - Effective date is used to apply correct price
 * - Soft deletes preserve audit history
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';

export type PriceDocument = HydratedDocument<Price>;

@Schema({ collection: 'price_master' })
export class Price {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, trim: true, type: String })
  priceId!: string;

  /* ======================================================
   * PRODUCT
   * ====================================================== */

  @Prop({ required: true, trim: true, type: String, ref: 'Product' })
  productId!: string;

  /* ======================================================
   * CATEGORY
   * ====================================================== */

  @Prop({ required: true, trim: true, type: String })
  categoryName!: string;

  @Prop({ required: true, trim: true, type: String })
  categoryCode!: string;

  /* ======================================================
   * PRICE
   * ====================================================== */

  @Prop({ required: true, type: Number, default: 0 })
  priceInclVat!: number;

  @Prop({ required: true, type: Number, default: 0 })
  priceExclVat!: number;

  /* ======================================================
   * EFFECTIVE DATE
   * ====================================================== */

  @Prop({ required: true, type: Date })
  effectiveDate!: Date;

  /* ======================================================
   * PRICE FLAG
   * ====================================================== */

  @Prop({ required: true, trim: true, type: String })
  priceFlag!: string;
}

export const PriceSchema = SchemaFactory.createForClass(Price);

/* ======================================================
 * INDEXES
 * ====================================================== */

PriceSchema.index({ productId: 1 });
PriceSchema.index({ categoryCode: 1 });
PriceSchema.index({ effectiveDate: -1 });

PriceSchema.index(
  {
    productId: 1,
    categoryCode: 1,
    priceFlag: 1,
    effectiveDate: 1,
  },
  {
    unique: true,
  },
);