import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { RouteCustomerMappingStatus } from 'src/shared/enums/route-customer-mapping.enums';

export type RouteCustomerMappingDocument =
  HydratedDocument<RouteCustomerMapping>;

@Schema({ collection: 'route_customer_mappings' })
export class RouteCustomerMapping {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  mappingId!: string;

  /* ======================================================
   * RELATIONSHIP
   * ====================================================== */

  @Prop({
    required: true,
    index: true,
    ref: 'route_master',
    type: String,
  })
  routeId!: string;

  @Prop({
    required: true,
    index: true,
    ref: 'customer_master',
    type: String,
  })
  customerId!: string;

  /* ======================================================
   * ROUTE CONFIG
   * ====================================================== */

  // Visit order in route
  @Prop({
    required: true,
    min: 1,
    type: Number,
  })
  sequence!: number;

  /* ======================================================
   * LIFECYCLE (HISTORY SUPPORT)
   * ====================================================== */

  @Prop({
    type: String,
    enum: RouteCustomerMappingStatus,
    default: RouteCustomerMappingStatus.ACTIVE,
    index: true,
  })
  status!: RouteCustomerMappingStatus;

  @Prop({
    default: Date.now,
    type: Date,
  })
  effectiveFrom!: Date;

  @Prop({
    default: null,
    type: Date,
  })
  effectiveTo?: Date;
}

export const RouteCustomerMappingSchema =
  SchemaFactory.createForClass(RouteCustomerMapping);

RouteCustomerMappingSchema.index(
  { customerId: 1, status: 1 },
  {
    unique: true,
    partialFilterExpression: {
      status: RouteCustomerMappingStatus.ACTIVE,
    },
    name: 'unique_active_route_per_customer',
  },
);
