import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { RouteChangeRequestStatus } from 'src/shared/enums/route-change-request.enums';

export type RouteChangeRequestDocument = HydratedDocument<RouteChangeRequest>;

@Schema({ timestamps: true, collection: 'route_change_requests' })
export class RouteChangeRequest {
  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  routeChangeRequestId!: string;

  @Prop({ required: true, index: true, type: String })
  workSessionId!: string;

  @Prop({ required: true, index: true, type: String })
  userId!: string;

  @Prop({ type: String })
  userName?: string;

  @Prop({ required: true, index: true, type: String })
  managerId!: string;

  @Prop({ required: true, type: String })
  currentRouteId!: string;

  @Prop({ type: String })
  currentRouteName?: string;

  @Prop({ type: String })
  currentRouteSessionId?: string;

  @Prop({ required: true, index: true, type: String })
  requestedRouteId!: string;

  @Prop({ type: String })
  requestedRouteName?: string;

  @Prop({ required: true, type: Number, min: 0 })
  totalShops!: number;

  @Prop({ required: true, type: String })
  vanId!: string;

  @Prop({ type: String })
  vanName?: string;

  @Prop({ type: String })
  customerCategoryId?: string;

  @Prop({ type: String, maxlength: 500 })
  reason?: string;

  @Prop({
    required: true,
    type: String,
    enum: RouteChangeRequestStatus,
    default: RouteChangeRequestStatus.PENDING,
    index: true,
  })
  status!: RouteChangeRequestStatus;

  @Prop({ type: String })
  approvedRouteSessionId?: string;

  @Prop({ type: String })
  resolvedBy?: string;

  @Prop({ type: Date })
  resolvedAt?: Date;
}

export const RouteChangeRequestSchema =
  SchemaFactory.createForClass(RouteChangeRequest);

RouteChangeRequestSchema.index({ managerId: 1, status: 1, createdAt: -1 });
RouteChangeRequestSchema.index({ userId: 1, createdAt: -1 });
RouteChangeRequestSchema.index(
  { workSessionId: 1, status: 1 },
  {
    unique: true,
    partialFilterExpression: {
      status: RouteChangeRequestStatus.PENDING,
      isDeleted: false,
    },
  },
);
