import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { RouteSessionStatus } from 'src/shared/enums/route-session.enums';

export type RouteSessionDocument = HydratedDocument<RouteSession>;

@Schema({
  timestamps: true,
  collection: 'route_sessions',
})
export class RouteSession {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String, index: true })
  routeSessionId!: string;

  @Prop({ required: true, type: String, index: true })
  workSessionId!: string;

  @Prop({ required: true, type: String, index: true })
  userId!: string;

  @Prop({ type: String })
  userName?: string;

  @Prop({ required: true, type: String, index: true })
  vanId!: string;

  @Prop({ type: String })
  vanName?: string;

  /* ======================================================
   * ROUTE DETAILS
   * ====================================================== */

  @Prop({ required: true, type: String, index: true })
  routeId!: string;

  @Prop({ type: String })
  routeName?: string;

  @Prop({ type: String, index: true })
  customerCategoryId?: string;

  /* ======================================================
   * ROUTE PROGRESS ⭐
   * ====================================================== */

  @Prop({ required: true, type: Number, min: 0 })
  totalShops!: number;

  @Prop({ default: 0, type: Number, min: 0 })
  visitedShops!: number;

  // ❌ Removed remainingShops (calculate instead)

  /* ======================================================
   * SESSION TRACKING
   * ====================================================== */

  @Prop({
    type: String,
    enum: Object.values(RouteSessionStatus),
    default: RouteSessionStatus.ACTIVE,
    index: true,
  })
  status!: RouteSessionStatus;

  @Prop({ required: true, type: Date, index: true })
  startTime!: Date;

  @Prop({ type: Date })
  endTime?: Date;

  /* ======================================================
   * MIS SUPPORT ⭐
   * ====================================================== */

  @Prop({
    type: Date,
    default: Date.now,
    index: true,
  })
  sessionDate!: Date; // VERY IMPORTANT for reports

  /* ======================================================
   * OPTIONAL FLAGS
   * ====================================================== */

  @Prop({ type: Boolean, default: true, index: true })
  isActive!: boolean;
}

export const RouteSessionSchema = SchemaFactory.createForClass(RouteSession);

/* ======================================================
 * INDEXES (IMPORTANT 🚀)
 * ====================================================== */

// One active route per user
// RouteSessionSchema.index(
//   { userId: 1, isActive: 1 },
//   { unique: true, partialFilterExpression: { isActive: true } }
// );

// // MIS queries
// RouteSessionSchema.index({
//   userId: 1,
//   sessionDate: -1,
// });

// RouteSessionSchema.index({
//   routeId: 1,
//   sessionDate: -1,
// });
