import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { RouteStatus } from 'src/shared/enums/route.enums';

export type RouteDocument = HydratedDocument<Route>;

@Schema({ _id: false, timestamps: false })
export class RouteCustomer {
  @Prop({ required: true })
  customerId: string;

  @Prop({ required: true })
  sequence: number;
}

export const RouteCustomerSchema = SchemaFactory.createForClass(RouteCustomer);

@Schema({ timestamps: true, collection: 'route_master' })
export class Route {
  @AutoGenerated()
  @Prop({ required: true, unique: true })
  routeId: string;

  @Prop({ required: true, trim: true })
  name: string;

  @Prop({ required: true })
  beatId: string;

  @Prop({
    type: [RouteCustomerSchema],
    default: [],
  })
  associatedCustomers: RouteCustomer[];

  @Prop({
    required: true,
    enum: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'],
  })
  day: string;

  @Prop({ type: Number, default: 0 })
  distance: number;

  @Prop({
    type: String,
    enum: RouteStatus,
    default: RouteStatus.ACTIVE,
  })
  status: RouteStatus;
}

export const RouteSchema = SchemaFactory.createForClass(Route);
