import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';

import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';

import { RouteStatus } from 'src/shared/enums/route.enums';

export type RouteDocument = HydratedDocument<Route>;

@Schema({ _id: false, timestamps: false })
export class RouteCustomer {
  @Prop({ required: true, type: String })
  customerId!: string;

  @Prop({ required: true, type: Number, min: 1 })
  sequence!: number;
}

export const RouteCustomerSchema = SchemaFactory.createForClass(RouteCustomer);

@Schema({
  timestamps: true,
  collection: 'route_master',
})
export class Route {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({
    required: true,
    unique: true,
    index: true,
    type: String,
  })
  routeId!: string;

  /* ======================================================
   * BASIC INFO
   * ====================================================== */

  @Prop({
    required: true,
    trim: true,
    type: String,
  })
  name!: string;

  /* ======================================================
   * LOCATION
   * ====================================================== */

  @Prop({
    type: String,
    index: true,
  })
  countryId!: string;

  @Prop({
    type: String,
    index: true,
  })
  customerCategoryId!: string;

  @Prop({
    type: String,
    index: true,
  })
  provinceId!: string;

  @Prop({
    type: String,
    index: true,
  })
  marketId!: string;

  @Prop({
    type: Number,
    default: 0,
  })
  outletCount!: number;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: RouteStatus,
    default: RouteStatus.ACTIVE,
    index: true,
  })
  status!: RouteStatus;
}

export const RouteSchema = SchemaFactory.createForClass(Route);
