/**
 * Route Session Collection
 * --------------------------------
 * Purpose : Track selected route for a user (per day/session)
 * Used by : RETAIL / FIELD SALES
 *
 * Contains:
 * - User & route mapping
 * - Route progress (total vs visited shops)
 * - Route start & end time
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { RouteSessionStatus } from 'src/shared/enums/route-session.enums';

export type RouteSessionDocument = HydratedDocument<RouteSession>;

@Schema({ timestamps: true, collection: 'route_sessions' })
export class RouteSession {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  routeSessionId: string;

  @Prop({ required: true, type: String })
  workSessionId: string;

  @Prop({ required: true, type: String })
  userId: string;

  @Prop({ type: String })
  userName: string;

  @Prop({ required: true, type: String })
  vanId: string;

  @Prop({ type: String })
  vanName: string;

  /* ======================================================
   * ROUTE DETAILS
   * ====================================================== */

  @Prop({ required: true, type: String })
  routeId: string;

  @Prop({ type: String })
  routeName: string;

  /* ======================================================
   * ROUTE PROGRESS ⭐
   * ====================================================== */

  // Total shops in this route
  @Prop({ required: true, type: Number })
  totalShops: number;

  // Number of shops visited
  @Prop({ default: 0, type: Number })
  visitedShops: number;

  // Remaining shops (optional but useful)
  @Prop({ default: 0, type: Number })
  remainingShops: number;

  /* ======================================================
   * SESSION TRACKING
   * ====================================================== */

  @Prop({
    type: String,
    enum: RouteSessionStatus,
    default: RouteSessionStatus.ACTIVE,
  })
  status: RouteSessionStatus;

  @Prop({ required: true, type: Date })
  startTime: Date;

  @Prop({ type: Date })
  endTime: Date;
}

export const RouteSessionSchema = SchemaFactory.createForClass(RouteSession);

/* ======================================================
 * INDEXES
 * ====================================================== */

// One active route per user
RouteSessionSchema.index({ userId: 1, isActive: 1 });
