import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { RouteStatus } from 'src/shared/enums/route.enums';

export type RouteDocument = HydratedDocument<Route>;

@Schema({ timestamps: true, collection: 'route_master' })
export class Route {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  routeId: String;

  /* ======================================================
   * BASIC INFO
   * ====================================================== */

  @Prop({ required: true, trim: true, type: String })
  name: String;

  @Prop({ required: true, index: true, type: String })
  beatId: string;

  /* ======================================================
   * ROUTE METADATA
   * ====================================================== */

  @Prop({ type: Number, default: 0 })
  distance: number;

  // Optional optimization
  @Prop({ type: Number, default: 0 })
  customerCount: number;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: RouteStatus,
    default: RouteStatus.ACTIVE,
    index: true,
  })
  status: RouteStatus;
}

export const RouteSchema = SchemaFactory.createForClass(Route);
