/**
 * Route Session Collection
 * --------------------------------
 * Purpose : Track selected route for a user (per day/session)
 * Used by : RETAIL / FIELD SALES
 *
 * Contains:
 * - User & route mapping
 * - Route progress (total vs visited shops)
 * - Route start & end time
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { RouteSessionStatus } from 'src/shared/enums/route-session.enums';

export type RouteSessionDocument = HydratedDocument<RouteSession>;

@Schema({ timestamps: true, collection: 'route_sessions' })
export class RouteSession {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true })
  routeSessionId: String;

  @Prop({ required: true })
  workSessionId: String;

  @Prop({ required: true })
  userId: String;

  @Prop()
  userName: String;

  @Prop({ required: true })
  vanId: String;

  @Prop()
  vanName: String;

  /* ======================================================
   * ROUTE DETAILS
   * ====================================================== */

  @Prop({ required: true })
  routeId: String;

  @Prop()
  routeName: String;

  /* ======================================================
   * ROUTE PROGRESS ⭐
   * ====================================================== */

  // Total shops in this route
  @Prop({ required: true })
  totalShops: Number;

  // Number of shops visited
  @Prop({ default: 0 })
  visitedShops: Number;

  // Remaining shops (optional but useful)
  @Prop({ default: 0 })
  remainingShops: Number;

  /* ======================================================
   * SESSION TRACKING
   * ====================================================== */

  @Prop({
    type: String,
    enum: RouteSessionStatus,
    default: RouteSessionStatus.ACTIVE,
  })
  status: RouteSessionStatus;

  @Prop({ required: true })
  startTime: Date;

  @Prop()
  endTime: Date;
}

export const RouteSessionSchema = SchemaFactory.createForClass(RouteSession);

/* ======================================================
 * INDEXES
 * ====================================================== */

// One active route per user
RouteSessionSchema.index({ userId: 1, isActive: 1 });
