import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import {
  SalePaymentStatus,
  SaleStatus,
  SaleType,
} from 'src/shared/enums/sale.enums';

export type SaleDocument = HydratedDocument<Sale>;

@Schema({ collection: 'sales' })
export class Sale {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ type: String, required: true, unique: true, index: true })
  saleId!: string;

  /* ======================================================
   * REFERENCES
   * ====================================================== */

  @Prop({ type: String, required: true, index: true })
  vanId!: string;

  @Prop({ type: String, required: true, index: true })
  visitId!: string;

  @Prop({ type: String, required: true, index: true })
  vanName!: string;

  @Prop({ type: String, required: true, index: true })
  customerId!: string;

  @Prop({ type: String, required: true, index: true })
  customerName!: string;

  /* ======================================================
   * EMPLOYEES
   * ====================================================== */

  @Prop({
    type: [
      {
        employeeId: {
          type: String,
          required: true,
          trim: true,
        },
        employeeName: {
          type: String,
          required: true,
          trim: true,
        },
        role: {
          type: String,
          required: true,
          trim: true,
        },
      },
    ],
    required: true,
    default: [],
  })
  employees!: {
    employeeId: string;
    employeeName: string;
    role: string;
  }[];

  @Prop({ type: Date, required: true, index: true })
  date!: Date;

  /* ======================================================
   * TOTALS
   * ====================================================== */

  @Prop({ type: Number, default: 0 })
  totalCases!: number;

  @Prop({ type: Number, default: 0 })
  netCases!: number;

  @Prop({ type: Number, default: 0 })
  totalPieces!: number;

  @Prop({ type: Number, required: true })
  totalQty!: number;

  @Prop({ type: Number, required: true })
  totalWeight!: number;

  @Prop({ type: Number, required: true })
  totalValue!: number;

  /* ======================================================
   * RETURNS
   * ====================================================== */

  @Prop({ type: Number, default: 0 })
  totalReturnCases!: number;

  @Prop({ type: Number, default: 0 })
  totalReturnPieces!: number;

  @Prop({ type: Number, default: 0 })
  totalReturnQty!: number;

  /* ======================================================
   * PAYMENT
   * ====================================================== */

  @Prop({
    type: String,
    enum: SaleType,
    default: SaleType.CASH,
    index: true,
  })
  type!: SaleType;

  @Prop({
    type: String,
    enum: SalePaymentStatus,
    default: SalePaymentStatus.UNPAID,
    index: true,
  })
  paymentStatus!: SalePaymentStatus;

  @Prop({ type: Number, default: 0 })
  paidAmount!: number;

  @Prop({ type: Number, default: 0 })
  pendingAmount!: number;

  /* ======================================================
   * META
   * ====================================================== */

  @Prop({ type: String })
  remark?: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: SaleStatus,
    default: SaleStatus.COMPLETED,
    index: true,
  })
  status!: SaleStatus;
}

export const SaleSchema = SchemaFactory.createForClass(Sale);

/* ======================================================
 * INDEXES
 * ====================================================== */

SaleSchema.index(
  { vanId: 1, customerId: 1, date: 1 },
  { name: 'idx_customer_sales_daily' },
);

SaleSchema.index(
  { 'employees.employeeId': 1, date: 1 },
  { name: 'idx_employee_sales_date' },
);

SaleSchema.index(
  { 'employees.role': 1, date: 1 },
  { name: 'idx_employee_role_sales_date' },
);
