import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Schema as MongooseSchema } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import {
  SalePaymentStatus,
  SaleStatus,
  SaleType,
} from 'src/shared/enums/sale.enums';
import { ErpSyncStatus } from 'src/shared/enums/stock-sales.enums';

export type SaleDocument = HydratedDocument<Sale>;

const SalePositionHierarchySchema = new MongooseSchema(
  {
    level: { type: Number, required: true, min: 1 },
    positionId: { type: String, required: true, trim: true },
    positionName: { type: String, required: true, trim: true },
    employeeId: { type: String, trim: true },
    employeeName: { type: String, trim: true },
  },
  { _id: false, timestamps: false },
);

@Schema({ collection: 'sales' })
export class Sale {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ type: String, required: true, unique: true, index: true })
  saleId!: string;

  /* ======================================================
   * REFERENCES
   * ====================================================== */

  @Prop({ type: String, required: true, index: true })
  vanId!: string;

  @Prop({ type: String, required: true, index: true })
  visitId!: string;

  @Prop({ type: String, required: true, index: true })
  vanName!: string;

  @Prop({ type: String, required: true, index: true })
  customerId!: string;

  @Prop({ type: String, required: true, index: true })
  customerName!: string;

  @Prop({
    type: [SalePositionHierarchySchema],
    required: true,
    default: [],
  })
  positionHierarchy!: {
    level: number;
    positionId: string;
    positionName: string;
    employeeId?: string;
    employeeName?: string;
  }[];

  @Prop({ type: Date, required: true, index: true })
  date!: Date;

  /* ======================================================
   * TOTALS
   * ====================================================== */

  @Prop({ type: Number, default: 0 })
  totalCases!: number;

  @Prop({ type: Number, default: 0 })
  netCases!: number;

  @Prop({ type: Number, default: 0 })
  totalPieces!: number;

  @Prop({ type: Number, required: true })
  totalQty!: number;

  @Prop({ type: Number, required: true })
  totalWeight!: number;

  /** Gross sale value before scheme discounts. */
  @Prop({ type: Number, default: 0 })
  subtotal!: number;

  @Prop({ type: [String], default: [], index: true })
  schemeIds!: string[];

  @Prop({ type: [String], default: [] })
  schemeNames!: string[];

  @Prop({ type: Number, default: 0 })
  schemeDiscountAmount!: number;

  @Prop({
    type: [
      {
        schemeId: { type: String, required: true },
        schemeName: { type: String, required: true, trim: true },
        schemeType: { type: String, required: true, trim: true },
        minimumQuantity: { type: Number, default: 0 },
        discountPercent: { type: Number },
        discountValue: { type: Number },
        buyQty: { type: Number },
        discountAmount: { type: Number, default: 0 },
        freeQty: { type: Number, default: 0 },
        freeProductId: { type: String },
        freeProductName: { type: String, trim: true },
      },
    ],
    default: [],
  })
  schemes!: {
    schemeId: string;
    schemeName: string;
    schemeType: string;
    minimumQuantity: number;
    discountPercent?: number;
    discountValue?: number;
    buyQty?: number;
    discountAmount: number;
    freeQty: number;
    freeProductId?: string;
    freeProductName?: string;
  }[];

  /** Net sale value after scheme discounts. */
  @Prop({ type: Number, required: true })
  totalValue!: number;

  /* ======================================================
   * RETURNS
   * ====================================================== */

  @Prop({ type: Number, default: 0 })
  totalReturnCases!: number;

  @Prop({ type: Number, default: 0 })
  totalReturnPieces!: number;

  @Prop({ type: Number, default: 0 })
  totalReturnQty!: number;

  /* ======================================================
   * PAYMENT
   * ====================================================== */

  @Prop({
    type: String,
    enum: SaleType,
    default: SaleType.CASH,
    index: true,
  })
  type!: SaleType;

  @Prop({
    type: String,
    enum: SalePaymentStatus,
    default: SalePaymentStatus.UNPAID,
    index: true,
  })
  paymentStatus!: SalePaymentStatus;

  @Prop({ type: Number, default: 0 })
  paidAmount!: number;

  @Prop({ type: Number, default: 0 })
  pendingAmount!: number;

  /* ======================================================
   * META
   * ====================================================== */

  @Prop({ type: String })
  remark?: string;

  @Prop({
    type: String,
    enum: ErpSyncStatus,
    default: ErpSyncStatus.PENDING,
    index: true,
  })
  erpSyncStatus!: ErpSyncStatus;

  @Prop({ type: Number, default: 0 })
  erpSyncAttempts!: number;

  @Prop({ type: Date })
  erpSyncedAt?: Date;

  @Prop({ type: Date })
  erpLastSyncAttemptAt?: Date;

  @Prop({ type: String })
  erpSyncError?: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: SaleStatus,
    default: SaleStatus.COMPLETED,
    index: true,
  })
  status!: SaleStatus;
}

export const SaleSchema = SchemaFactory.createForClass(Sale);

/* ======================================================
 * INDEXES
 * ====================================================== */

SaleSchema.index(
  { vanId: 1, customerId: 1, date: 1 },
  { name: 'idx_customer_sales_daily' },
);

SaleSchema.index(
  { 'positionHierarchy.employeeId': 1, date: 1 },
  { name: 'idx_position_hierarchy_employee_sales_date' },
);

SaleSchema.index(
  { 'positionHierarchy.positionId': 1, date: 1 },
  { name: 'idx_position_hierarchy_sales_date' },
);
