/**
 * Schemes Collection
 * ------------------
 * Purpose : Sales promotion / discount scheme master
 * Used by : BACK_OFFICE / ADMIN / SALES / APP
 *
 * Contains:
 * - Scheme identity and validity period
 * - Independent applicability on: category, sub-category, product,
 *   province, route and van
 * - Benefit definition (discount or buy-x-get-y / free item)
 *
 * Notes:
 * - Product/category dimensions form one targeting group and
 *   province/route/van dimensions form another.
 * - Empty product targeting means all products; empty geography targeting
 *   means all locations. Populated arrays restrict their respective group.
 * - Soft deletes preserve audit history
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';

import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { SchemeStatus, SchemeType } from 'src/shared/enums/scheme.enums';

export type SchemeDocument = HydratedDocument<Scheme>;

@Schema({ collection: 'scheme_master', timestamps: true })
export class Scheme {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, trim: true, type: String })
  schemeId!: string;

  @Prop({ required: true, trim: true, type: String })
  name!: string;

  @Prop({ trim: true, type: String })
  description?: string;

  /* ======================================================
   * PRODUCT APPLICABILITY (independent, each optional)
   * ====================================================== */

  // Category-wise applicability; all product arrays empty means all products
  @Prop({ type: [String], ref: 'ProductCategory', default: [], index: true })
  categoryIds!: string[];

  // Sub-category-wise applicability
  @Prop({ type: [String], ref: 'ProductCategory', default: [], index: true })
  subCategoryIds!: string[];

  // Product-wise applicability
  @Prop({ type: [String], ref: 'Product', default: [], index: true })
  productIds!: string[];

  /* ======================================================
   * GEOGRAPHY APPLICABILITY (independent, each optional)
   * ====================================================== */

  // Province-wise applicability; all geography arrays empty means all locations
  @Prop({ type: [String], ref: 'Province', default: [], index: true })
  provinceIds!: string[];

  // Route-wise applicability; empty means not applicable to any route
  @Prop({ type: [String], ref: 'Route', default: [], index: true })
  routeIds!: string[];

  // Van-wise applicability; empty means not applicable to any van
  @Prop({ type: [String], ref: 'Van', default: [], index: true })
  vanIds!: string[];

  /* ======================================================
   * BENEFIT DEFINITION
   * ====================================================== */

  @Prop({ required: true, type: String, enum: SchemeType })
  schemeType!: SchemeType;

  // Minimum purchase quantity/cases to trigger the scheme
  @Prop({ type: Number, min: 0, default: 0 })
  minQty!: number;

  // Percentage discount, used when schemeType is DISCOUNT_PERCENT
  @Prop({ type: Number, min: 0, max: 100 })
  discountPercent?: number;

  // Flat value discount, used when schemeType is DISCOUNT_VALUE
  @Prop({ type: Number, min: 0 })
  discountValue?: number;

  // Buy quantity, used when schemeType is BUY_X_GET_Y
  @Prop({ type: Number, min: 0 })
  buyQty?: number;

  // Free/get quantity, used when schemeType is BUY_X_GET_Y or FREE_ITEM
  @Prop({ type: Number, min: 0 })
  freeQty?: number;

  // Free item product reference, used when the free item differs from the purchased product
  @Prop({ type: String, ref: 'Product' })
  freeProductId?: string;

  @Prop({ trim: true, type: String })
  freeProductName?: string;

  /* ======================================================
   * VALIDITY PERIOD
   * ====================================================== */

  @Prop({ required: true, type: Date, index: true })
  startDate!: Date;

  @Prop({ required: true, type: Date, index: true })
  endDate!: Date;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: SchemeStatus,
    default: SchemeStatus.ACTIVE,
    index: true,
  })
  status!: SchemeStatus;

  @Prop({ default: false, type: Boolean })
  isDeleted!: boolean;
}

export const SchemeSchema = SchemaFactory.createForClass(Scheme);

/* ======================================================
 * INDEXES
 * ====================================================== */

SchemeSchema.index({ categoryIds: 1 });
SchemeSchema.index({ subCategoryIds: 1 });
SchemeSchema.index({ productIds: 1 });
SchemeSchema.index({ provinceIds: 1 });
SchemeSchema.index({ routeIds: 1 });
SchemeSchema.index({ vanIds: 1 });
SchemeSchema.index({ startDate: 1, endDate: 1 });
SchemeSchema.index({ status: 1, isDeleted: 1 });
