import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { SegmentationStatus } from 'src/shared/enums/segmentation.enums';

export type SegmentationDocument = HydratedDocument<Segmentation>;

@Schema({ collection: 'segmentation_master', timestamps: true })
export class Segmentation {
  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  segmentationId!: string;

  @Prop({ required: true, unique: true, type: String, trim: true })
  name!: string;

  @Prop({
    type: String,
    enum: SegmentationStatus,
    default: SegmentationStatus.ACTIVE,
  })
  status!: SegmentationStatus;
}

export const SegmentationSchema = SchemaFactory.createForClass(Segmentation);
