/**
 * Shop Visit Collection
 * --------------------------------
 * Purpose : Track each shop visit within a route
 * Used by : RETAIL / FIELD SALES
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import {
  ShopVisitStatus,
  ShopVisitType,
} from 'src/shared/enums/shop-visit.enums';

export type ShopVisitDocument = HydratedDocument<ShopVisit>;

export class LocationPoint {
  @Prop({ type: Number })
  latitude?: number;

  @Prop({ type: Number })
  longitude?: number;

  @Prop({ type: Number })
  accuracy?: number;

  @Prop({ type: Number })
  altitude?: number;

  @Prop({ type: Number })
  speed?: number;

  @Prop({ type: Date })
  capturedAt?: Date;
}

@Schema({ timestamps: true, collection: 'shop_visits' })
export class ShopVisit {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  visitId!: string;

  /* ======================================================
   * RELATIONSHIP
   * ====================================================== */

  @Prop({ required: true, type: String })
  routeSessionId!: string;

  @Prop({ required: true, type: String })
  workSessionId!: string;

  @Prop({ required: true, type: String })
  employeeId!: string;

  @Prop({ type: String })
  employeeName!: string;

  @Prop({ required: true, type: String })
  vanId!: string;

  @Prop({ type: String })
  vanName!: string;

  /* ======================================================
   * SHOP DETAILS
   * ====================================================== */

  @Prop({ required: true, type: String })
  outletId!: string;

  @Prop({ type: String })
  outletName!: string;

  @Prop({ type: Number })
  sequence!: number;

  @Prop({ type: Number })
  orderCount!: number;

  @Prop({ type: Number })
  paymentCount!: number;

  /* ======================================================
   * VISIT TRACKING
   * ====================================================== */

  // Check-in time
  @Prop({ required: true, type: Date })
  checkInTime!: Date;

  // Check-out time
  @Prop({ type: Date })
  checkOutTime!: Date;

  @Prop({ type: Object })
  checkInLocation?: LocationPoint;

  @Prop({ type: Object })
  checkOutLocation?: LocationPoint;

  // Visit Type
  @Prop({
    type: String,
    enum: ShopVisitType,
    default: ShopVisitType.ON_SITE,
  })
  visitType!: ShopVisitType;

  // Visit status
  @Prop({
    type: String,
    enum: ShopVisitStatus,
    default: ShopVisitStatus.ACTIVE,
  })
  status!: ShopVisitStatus;
}

export const ShopVisitSchema = SchemaFactory.createForClass(ShopVisit);

/* ======================================================
 * INDEXES
 * ====================================================== */

ShopVisitSchema.index({ routeSessionId: 1 });

// // Prevent duplicate active visit
// ShopVisitSchema.index({
//   routeSessionId: 1,
//   outletId: 1,
//   status: 1,
// });
