/**
 * Shop Visit Collection
 * --------------------------------
 * Purpose : Track each shop visit within a route
 * Used by : RETAIL / FIELD SALES
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { ShopVisitStatus } from 'src/shared/enums/shop-visit.enums';


export type ShopVisitDocument = HydratedDocument<ShopVisit>;

@Schema({ timestamps: true, collection: 'shop_visits' })
export class ShopVisit {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true })
  visitId: string;

  /* ======================================================
   * RELATIONSHIP
   * ====================================================== */

  @Prop({ required: true })
  routeSessionId: string;

  @Prop({ required: true })
  userId: string;

  @Prop()
  userName: string;

  @Prop({ required: true })
  vanId: string;

  @Prop()
  vanName: string;

  /* ======================================================
   * SHOP DETAILS
   * ====================================================== */

  @Prop({ required: true })
  shopId: string;

  @Prop()
  shopName: string;

  @Prop()
  sequence: number;

  /* ======================================================
   * VISIT TRACKING
   * ====================================================== */

  // Check-in time
  @Prop({ required: true })
  checkInTime: Date;

  // Check-out time
  @Prop()
  checkOutTime: Date;

  // Visit status
  @Prop({
    type: String,
    enum: ShopVisitStatus,
    default: ShopVisitStatus.ACTIVE,
  })
  status: ShopVisitStatus;
}

export const ShopVisitSchema =
  SchemaFactory.createForClass(ShopVisit);

/* ======================================================
 * INDEXES
 * ====================================================== */

ShopVisitSchema.index({ routeSessionId: 1 });

// Prevent duplicate active visit
ShopVisitSchema.index({ routeSessionId: 1, shopId: 1, status: 1 });