import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { StockCountStatus } from 'src/shared/enums/stock-count.enums';

export type StockCountDocument = HydratedDocument<StockCount>;

@Schema({ timestamps: true, collection: 'physical_counts' })
export class StockCount {
  /* ======================================================
   * IDENTIFIERS
   * ====================================================== */

  @AutoGenerated()
  @Prop({ type: String, required: true, unique: true })
  stockCountId!: string;

  @Prop({ type: String, required: true, unique: true, index: true })
  workSessionId!: string;

  @Prop({ type: String, required: true, index: true })
  vanId!: string;

  @Prop({ type: String, required: true })
  employeeId!: string;

  /* ======================================================
   * DATE
   * ====================================================== */

  @Prop({ type: Date, required: true, index: true })
  date!: Date;

  /* ======================================================
   * SYSTEM TOTALS (EXPECTED)
   * ====================================================== */

  @Prop({ type: Number, default: 0 })
  systemQty!: number;

  @Prop({ type: Number, default: 0 })
  systemCase!: number;

  @Prop({ type: Number, default: 0 })
  systemPiece!: number;

  @Prop({ type: Number, default: 0 })
  systemWeight!: number;

  @Prop({ type: Number, default: 0 })
  systemValue!: number;

  /* ======================================================
   * COUNTED TOTALS (PHYSICAL)
   * ====================================================== */

  @Prop({ type: Number, default: 0 })
  countedQty!: number;

  @Prop({ type: Number, default: 0 })
  countedCase!: number;

  @Prop({ type: Number, default: 0 })
  countedPiece!: number;

  @Prop({ type: Number, default: 0 })
  countedWeight!: number;

  @Prop({ type: Number, default: 0 })
  countedValue!: number;

  /* ======================================================
   * VARIANCE TOTALS
   * ====================================================== */

  @Prop({ type: Number, default: 0 })
  varianceQty!: number;

  @Prop({ type: Number, default: 0 })
  varianceCase!: number;

  @Prop({ type: Number, default: 0 })
  variancePiece!: number;

  @Prop({ type: Number, default: 0 })
  varianceWeight!: number;

  @Prop({ type: Number, default: 0 })
  varianceValue!: number;

  /* ======================================================
   * META
   * ====================================================== */

  @Prop()
  remark?: string;

  @Prop({ type: String })
  createdById?: string;

  @Prop({ type: String })
  updatedById?: string;

  @Prop({ type: String })
  approvedById?: string;

  @Prop({ type: Date })
  approvedAt?: Date;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: StockCountStatus,
    default: StockCountStatus.DRAFT,
    index: true,
  })
  status!: StockCountStatus;
}

export const StockCountSchema = SchemaFactory.createForClass(StockCount);

/* ======================================================
 * INDEXES
 * ====================================================== */

// One stock count per van per day
StockCountSchema.index(
  { vanId: 1, date: 1 },
  { unique: true, name: 'unique_van_stock_count_per_day' },
);
