/**
 * Physical Counts Collection
 * --------------------------
 * Purpose : Capture end-of-day physical stock per van
 * Used by : SALES / SUPERVISOR / BACK_OFFICE
 *
 * Contains:
 * - Physical count identity
 * - Van & employee mapping
 * - Physical stock totals
 * - Approval workflow state
 *
 * Notes:
 * - One record per van per day
 * - Generates Stock Sales after approval
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { StockCountStatus } from 'src/shared/enums/stock-count.enums';

export type StockCountDocument = HydratedDocument<StockCount>;

@Schema({ timestamps: true, collection: 'physical_counts' })
export class StockCount {
  /* ======================================================
   * IDENTIFIERS
   * ====================================================== */

  @AutoGenerated()
  @Prop({ type: String, required: true, unique: true })
  stockCountId: string;

  @Prop({ type: String, required: true })
  vanId: string;

  @Prop({ type: String, required: true })
  employeeId: string;

  /* ======================================================
   * TOTALS
   * ====================================================== */

  @Prop({ type: Number, default: 0 })
  totalQuantity: number;

  @Prop({ type: Number, default: 0 })
  totalWeight: number;

  @Prop({ type: Number, default: 0 })
  totalValue: number;

  @Prop({ type: String })
  updatedById: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: StockCountStatus,
    default: StockCountStatus.DRAFT,
  })
  status: StockCountStatus;
}

export const StockCountSchema = SchemaFactory.createForClass(StockCount);
