/**
 * Stock Sales Collection
 * ---------------------
 * Purpose : Store daily van-wise sales derived from stock movement
 * Used by : BACK_OFFICE / ADMIN / ERP / ACCOUNTS
 *
 * Contains:
 * - Stock sales identity
 * - Van reference
 * - Sales date
 * - Physical count reference
 * - Total physical stock
 * - Total sales
 * - Variance totals
 * - ERP sync status
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import {
  ErpSyncStatus,
  StockSalesStatus,
} from 'src/shared/enums/stock-sales.enums';

export type StockSalesDocument = HydratedDocument<StockSales>;

@Schema({ timestamps: true, collection: 'stock_sales' })
export class StockSales {
  @AutoGenerated()
  @Prop({ required: true, unique: true , type: String})
  stockSalesId: string;

  @Prop({ required: true, unique: true , type: String})
  stockSalesNumber: string;

  @Prop({ required: true, type: String })
  physicalCountId: string;

  @Prop({ required: true, type: String })
  vanId: string;

  @Prop({ required: true, type: String })
  employeeId: string;

  @Prop({ type: Number, default: 0 })
  totalPhysicalStock: number;

  @Prop({ type: Number, default: 0 })
  totalPhysicalStockWeight: number;

  @Prop({ type: Number, default: 0 })
  totalPhysicalStockValue: number;

  @Prop({ type: Number, default: 0 })
  totalSalesQuantity: number;

  @Prop({ type: Number, default: 0 })
  totalSalesValue: number;

  @Prop({ type: Number, default: 0 })
  totalSalesWeight: number;

  @Prop({ type: Number, default: 0 })
  totalVariance: number;

  @Prop({ type: Number, default: 0 })
  totalVarianceWeight: number;

  @Prop({ type: Boolean, default: false })
  hasVariance: boolean;

  @Prop({ type: Number, default: 0 })
  totalSystemStock: number;

  @Prop({ type: Number, default: 0 })
  totalSystemStockWeight: number;

  @Prop({ type: Number, default: 0 })
  totalSystemStockValue: number;

  @Prop({
    type: String,
    enum: StockSalesStatus,
    default: StockSalesStatus.DRAFT,
  })
  status: StockSalesStatus;

  @Prop({
    type: String,
    enum: ErpSyncStatus,
    default: ErpSyncStatus.PENDING,
  })
  erpSyncStatus: ErpSyncStatus;

  @Prop({ type: Date })
  erpSyncedAt?: Date;
}

export const StockSalesSchema = SchemaFactory.createForClass(StockSales);

StockSalesSchema.index({ vanId: 1, salesDate: 1 }, { unique: true });
