import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { VanChangeRequestStatus } from 'src/shared/enums/van-change-request.enums';

export type VanChangeRequestDocument = HydratedDocument<VanChangeRequest>;

@Schema({ timestamps: true, collection: 'van_change_requests' })
export class VanChangeRequest {
  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  vanChangeRequestId!: string;

  @Prop({ required: true, index: true, type: String })
  workSessionId!: string;

  @Prop({ required: true, index: true, type: String })
  userId!: string;

  @Prop({ type: String })
  userName?: string;

  @Prop({ required: true, type: String })
  currentVanId!: string;

  @Prop({ type: String })
  currentVanName?: string;

  @Prop({ required: true, index: true, type: String })
  requestedVanId!: string;

  @Prop({ type: String })
  requestedVanName?: string;

  @Prop({ type: String, maxlength: 500 })
  reason?: string;

  @Prop({
    required: true,
    type: String,
    enum: VanChangeRequestStatus,
    default: VanChangeRequestStatus.PENDING,
    index: true,
  })
  status!: VanChangeRequestStatus;

  @Prop({ type: String })
  resolvedBy?: string;

  @Prop({ type: Date })
  resolvedAt?: Date;
}

export const VanChangeRequestSchema =
  SchemaFactory.createForClass(VanChangeRequest);

VanChangeRequestSchema.index({ workSessionId: 1, createdAt: -1 });
VanChangeRequestSchema.index({ userId: 1, status: 1, createdAt: -1 });
VanChangeRequestSchema.index(
  { workSessionId: 1, status: 1 },
  {
    unique: true,
    partialFilterExpression: {
      status: VanChangeRequestStatus.PENDING,
      isDeleted: false,
    },
  },
);
