/**
 * Van Daily Stock Collection
 * -------------------------
 * Purpose : Store opening & closing stock per van per day
 * Used by : BACK_OFFICE / ADMIN / SALES
 *
 * Contains:
 * - Date reference
 * - Van reference
 * - Product reference
 * - Opening stock
 * - Inbound quantity
 * - Outbound quantity
 * - Adjustment quantity
 * - Closing stock
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { VanDailyStockStatus } from 'src/shared/enums/van-daily-stock.enums';

export type VanDailyStockDocument = HydratedDocument<VanDailyStock>;

@Schema({ collection: 'van_daily_stock', timestamps: true })
export class VanDailyStock {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  vanDailyStockId!: string;

  @Prop({ required: true, index: true, type: String })
  workSessionId!: string;

  /* ======================================================
   * DATE
   * ====================================================== */

  @Prop({ required: true, index: true, type: Date })
  date!: Date;

  /* ======================================================
   * VAN, EMPLOYEE & PRODUCT REFERENCES
   * ====================================================== */

  @Prop({ required: true, index: true, type: String })
  employeeId!: string;

  @Prop({ required: true, index: true, type: String })
  vanId!: string;

  @Prop({ required: true, index: true, type: String })
  productId!: string;

  @Prop({ type: Number, required: true })
  unitQtyInCase!: number;

  @Prop({ type: Number, required: true })
  piecePrice!: number;

  @Prop({ type: Number, required: true })
  pieceNetWeight!: number;

  /* ======================================================
   * STOCK SNAPSHOT
   * ====================================================== */

  @Prop({
    type: Number,
    required: true,
    default: 0,
    min: 0,
  })
  openingQty!: number;

  @Prop({
    type: Number,
    required: true,
    default: 0,
    min: 0,
  })
  inQty!: number;

  @Prop({
    type: Number,
    required: true,
    default: 0,
    min: 0,
  })
  outQty!: number;

  @Prop({
    type: Number,
    required: true,
    default: 0,
    min: 0,
  })
  adjustmentQty!: number;

  @Prop({
    type: Number,
    required: true,
    default: 0,
    min: 0,
  })
  closingQty!: number;

  /* ======================================================
   * META
   * ====================================================== */

  @Prop()
  remark?: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: VanDailyStockStatus,
    default: VanDailyStockStatus.DRAFT,
    index: true,
  })
  status!: VanDailyStockStatus;
}

export const VanDailyStockSchema = SchemaFactory.createForClass(VanDailyStock);

/**
 * One record per Van + Product + Day
 */
VanDailyStockSchema.index(
  { date: 1, vanId: 1, productId: 1, workSessionId: 1 },
  { unique: true, name: 'unique_van_daily_stock' },
);
