/**
 * Inventory Collection
 * --------------------
 * Purpose : Product stock management
 * Used by : BACK_OFFICE / ADMIN / SALES
 *
 * Contains:
 * - Inventory identity
 * - Product reference
 * - Stock quantities
 * - Settlement date
 * - Status
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { VanInventoryStatus } from 'src/shared/enums/van-inventory.enums';

export type VanInventoryDocument = HydratedDocument<VanInventory>;

/* ======================================================
 * INVENTORY SCHEMA
 * ====================================================== */

@Schema({ timestamps: true, collection: 'inventories' })
export class VanInventory {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true })
  inventoryId: string;

  /* ======================================================
   * PRODUCT REFERENCE
   * ====================================================== */

  @Prop({ required: true, index: true })
  productId: string;

  /* ======================================================
   * VAN REFERENCE
   * ====================================================== */
  @Prop({ required: true, index: true })
  vanId: string;

  /* ======================================================
   * QUANTITY DETAILS
   * ====================================================== */

  // Total stock quantity
  @Prop({
    required: true,
    min: 0.00001,
  })
  quantity: number;

  // Reserved quantity for orders (optional)
  @Prop({
    min: 0.0001,
    default: 0,
  })
  reservedQuantity?: number;

  /* ======================================================
   * SETTLEMENT
   * ====================================================== */

  // ISO settlement date (optional)
  @Prop()
  settlementDate?: Date;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: VanInventoryStatus,
    default: VanInventoryStatus.ACTIVE,
    index: true,
  })
  status: VanInventoryStatus;
}

export const VanInventorySchema = SchemaFactory.createForClass(VanInventory);
