/**
 * Van Inventory Top-Up Collection (Header)
 * ---------------------------------------
 * Purpose : Request & approve inventory loading from warehouse to van
 * Used by : BACK_OFFICE / ADMIN / SALES
 *
 * Flow :
 *  DRAFT → SUBMITTED → APPROVED → REJECTED
 *
 * On APPROVED:
 *  - Deduct warehouse_inventory
 *  - Increase van_inventory
 *  - Insert inventory_transactions
 *
 * Contains:
 * - Van & warehouse reference
 * - Business date
 * - Requested totals (qty / weight / value)
 * - Approved totals (qty / weight / value)
 * - Workflow status
 *
 * Notes:
 * - Line items are stored in van_inventory_topup_items
 * - All identifiers are stored as String (no ObjectId)
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { VanInventoryTopupStatus } from 'src/shared/enums/van-inventory-topup.enums';

export type VanInventoryTopupDocument = HydratedDocument<VanInventoryTopup>;

@Schema({ collection: 'van_inventory_topup', timestamps: true })
export class VanInventoryTopup {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  // Unique business identifier for top-up
  @AutoGenerated()
  @Prop({ type: String, required: true, unique: true, index: true })
  vanInventoryTopupId: string;

  /* ======================================================
   * REFERENCES
   * ====================================================== */

  // Van reference (vans.vanId)
  @Prop({ type: String, required: true, index: true })
  vanId: string;

  // Van reference (vans.vanId)
  @Prop({ type: String, required: true, index: true })
  vanName: string;

  // Van reference (vans.vanId)
  @Prop({ type: String, required: true, index: true })
  employeeId: string;

  // Warehouse reference (warehouses.warehouseId)
  @Prop({ type: String, required: true, index: true })
  warehouseId: string;

  // Business date of top-up (UTC)
  @Prop({ type: Date, required: true, index: true })
  date: Date;

  /* ======================================================
   * REQUESTED TOTALS (Derived from van_inventory_topup_items)
   * ====================================================== */

  // Sum of requestedQty
  @Prop({ type: Number, required: true })
  totalRequestedQty: number;

  // Sum of requestedWeight
  @Prop({ type: Number, required: true })
  totalRequestedWeight: number;

  // Sum of requestedValue
  @Prop({ type: Number, required: true })
  totalRequestedValue: number;

  /* ======================================================
   * APPROVED TOTALS (Derived from van_inventory_topup_items)
   * ====================================================== */

  // Sum of approvedQty
  @Prop({ type: Number, default: 0 })
  totalApprovedQty: number;

  // Sum of approvedWeight
  @Prop({ type: Number, default: 0 })
  totalApprovedWeight: number;

  // Sum of approvedValue
  @Prop({ type: Number, default: 0 })
  totalApprovedValue: number;

  /* ======================================================
   * META
   * ====================================================== */

  // Optional remark
  @Prop()
  remark?: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  // Workflow status
  @Prop({
    type: String,
    enum: VanInventoryTopupStatus,
    default: VanInventoryTopupStatus.DRAFT,
    index: true,
  })
  status: VanInventoryTopupStatus;
}

export const VanInventoryTopupSchema =
  SchemaFactory.createForClass(VanInventoryTopup);

/**
 * One Top-Up per Van per Business Date
 */
VanInventoryTopupSchema.index(
  { vanId: 1, date: 1 },
  { unique: true, name: 'unique_van_inventory_topup' },
);
