/**
 * Work Session Collection
 * --------------------------------
 * Purpose : Track user day start & end (attendance/session)
 * Used by : APP / ADMIN / REPORTING
 *
 * Contains:
 * - User identity
 * - Day start & end time
 * - Session status
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { WorkSessionStatus } from 'src/shared/enums/work-session.enums';

export type WorkSessionDocument = HydratedDocument<WorkSession>;

export class LocationPoint {
  @Prop({ type: Number })
  latitude?: number;

  @Prop({ type: Number })
  longitude?: number;

  @Prop({ type: Number })
  accuracy?: number;

  @Prop({ type: Number })
  altitude?: number;

  @Prop({ type: Number })
  speed?: number;

  @Prop({ type: Date })
  capturedAt?: Date;
}

@Schema({ timestamps: true, collection: 'work_sessions' })
export class WorkSession {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  // Unique session reference ID
  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  workSessionId!: string;

  // User who started the session
  @Prop({ required: true, type: String })
  userId!: string;

  // User name (for quick reference)
  @Prop({ type: String })
  userName!: string;

  // User who started the session
  @Prop({ required: true, type: String })
  vanId!: string;

  // User name (for quick reference)
  @Prop({ type: String })
  vanName!: string;

  @Prop({ type: String })
  requestedVanId?: string;

  @Prop({ type: String })
  requestedVanName?: string;

  @Prop({ type: String })
  vanChangeReason?: string;

  @Prop({
    type: String,
    enum: ['PENDING', 'APPROVED', 'REJECTED'],
  })
  vanChangeStatus?: 'PENDING' | 'APPROVED' | 'REJECTED';

  @Prop({ type: String })
  vanChangeApprovedBy?: string;

  @Prop({ type: Date })
  vanChangeApprovedAt?: Date;

  @Prop({ type: String })
  vanChangeRejectedBy?: string;

  @Prop({ type: Date })
  vanChangeRejectedAt?: Date;

  /* ======================================================
   * SESSION DETAILS
   * ====================================================== */

  // Day start time
  @Prop({ required: true, type: Date })
  dayStartTime!: Date;

  // Day end time
  @Prop({ type: Date })
  dayEndTime!: Date;

  @Prop({ type: String })
  dayStartImageMediaId?: string;

  @Prop({ type: String })
  dayStartImageUrl?: string;

  @Prop({ type: Object })
  dayStartLocation?: LocationPoint;

  @Prop({ type: Object })
  dayEndLocation?: LocationPoint;

  // Activity status
  @Prop({
    type: String,
    enum: WorkSessionStatus,
    default: WorkSessionStatus.ACTIVE,
  })
  status!: WorkSessionStatus;
}

export const WorkSessionSchema = SchemaFactory.createForClass(WorkSession);

/* ======================================================
 * INDEXES (Recommended)
 * ====================================================== */

// Prevent multiple active sessions per user
WorkSessionSchema.index({ userId: 1, isActive: 1 });

// Fast queries for reports
WorkSessionSchema.index({ userId: 1, dayStartTime: -1 });
WorkSessionSchema.index({ vanChangeStatus: 1, requestedVanId: 1 });
