/**
 * Work Session Collection
 * --------------------------------
 * Purpose : Track user day start & end (attendance/session)
 * Used by : APP / ADMIN / REPORTING
 *
 * Contains:
 * - User identity
 * - Day start & end time
 * - Session status
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { WorkSessionStatus } from 'src/shared/enums/work-session.enums';

export type WorkSessionDocument = HydratedDocument<WorkSession>;

@Schema({ timestamps: true, collection: 'work_sessions' })
export class WorkSession {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  // Unique session reference ID
  @AutoGenerated()
  @Prop({ required: true, unique: true, type: String })
  workSessionId: string;

  // User who started the session
  @Prop({ required: true, type: String })
  userId: string;

  // User name (for quick reference)
  @Prop({ type: String })
  userName: string;

  // User who started the session
  @Prop({ required: true, type: String })
  vanId: string;

  // User name (for quick reference)
  @Prop({ type: String })
  vanName: string;

  /* ======================================================
   * SESSION DETAILS
   * ====================================================== */

  // Day start time
  @Prop({ required: true, type: String })
  dayStartTime: Date;

  // Day end time
  @Prop({ type: String })
  dayEndTime: Date;

  // Activity status
  @Prop({
    type: String,
    enum: WorkSessionStatus,
    default: WorkSessionStatus.ACTIVE,
  })
  status: WorkSessionStatus;
}

export const WorkSessionSchema = SchemaFactory.createForClass(WorkSession);

/* ======================================================
 * INDEXES (Recommended)
 * ====================================================== */

// Prevent multiple active sessions per user
WorkSessionSchema.index({ userId: 1, isActive: 1 });

// Fast queries for reports
WorkSessionSchema.index({ userId: 1, dayStartTime: -1 });
