const { mapType } = require('../utils/type-mapper');

module.exports = ({ Entity, dtoFields, classComment, entity, embeddedSchemas = [] }) => {
  const swaggerImports = new Set(['ApiProperty', 'ApiPropertyOptional']);
  const validatorImports = new Set(['IsNotEmpty', 'IsOptional']);
  const transformerImports = new Set();
  const nestedDtoClasses = [];

  const enumImportsMap = new Map();

  // ✅ EXCLUDE SYSTEM FIELDS
  const EXCLUDED_FIELDS = new Set(['_id', 'id', 'createdAt', 'updatedAt', 'deletedAt']);

  let body = '';

  /* ======================================================
   * CLASS DOC
   * ====================================================== */
  const generateClassDoc = () => {
    return `/**
 * Create${Entity}Dto
 * =================
 * ${classComment || `DTO for creating ${Entity}`}
 */\n`;
  };

  body += generateClassDoc();

  /* ======================================================
   * NESTED DTO
   * ====================================================== */
  const generateNestedDtoClass = (schema) => {
    const className = `${schema.name}Dto`;
    let nested = `\nexport class ${className} {\n`;

    schema.fields.forEach((field) => {
      if (['_id', '__v', 'createdAt', 'updatedAt'].includes(field.name)) return;

      let tsType = field.tsType;

      if (field.isArray && tsType.endsWith('[]')) {
        tsType = tsType.replace(/\[\]$/, '');
      }

      if (field.isArray) tsType += '[]';

      nested += `  @ApiPropertyOptional({ type: ${field.isArray ? '[String]' : 'String'}, default: [] })\n`;
      nested += `  @IsOptional()\n`;

      if (field.isArray) {
        nested += `  @IsArray()\n`;
        nested += `  @IsString({ each: true })\n`;
        validatorImports.add('IsArray');
        validatorImports.add('IsString');
      }

      nested += `  ${field.name}?: ${tsType};\n\n`;
    });

    nested += `}\n`;
    return nested;
  };

  embeddedSchemas.forEach((schema) => {
    nestedDtoClasses.push(generateNestedDtoClass(schema));
  });

  /* ======================================================
   * MAIN DTO
   * ====================================================== */
  const fields = dtoFields?.create || [];

  for (const field of fields) {
    // ✅ skip system fields
    if (EXCLUDED_FIELDS.has(field.name)) continue;

    // ✅ skip AutoGenerated
    if (field.isAutoGenerated) continue;

    if (['system', 'auto', 'audit'].includes(field.source)) continue;

    const isRequired = field.isRequired && !field.hasDefaultValue;

    const mapped = mapType(field.tsType, {
      ...field,
      isRequired,
    });

    let validators = mapped.validator.split('\n').filter(Boolean);

    /* ---------- SAFE IMPORT HANDLING ---------- */
    if (mapped.extraImports?.length) {
      mapped.extraImports.forEach((imp) => {
        if (imp === field.enumType) return;
        if (imp === field.embeddedSchema?.name) return;

        if (imp === 'Type') transformerImports.add('Type');
        else validatorImports.add(imp);
      });
    }

    /* ---------- REQUIRED / OPTIONAL ---------- */
    if (!isRequired) {
      if (!validators.includes('@IsOptional()')) {
        validators.unshift('@IsOptional()');
      }
    } else {
      if (!validators.includes('@IsNotEmpty()')) {
        validators.unshift('@IsNotEmpty()');
      }
    }

    /* ---------- ARRAY ---------- */
    if (field.isArray) {
      if (!validators.some((v) => v.includes('@IsArray'))) {
        validators.unshift('@IsArray()');
        validatorImports.add('IsArray');
      }

      if (!validators.some((v) => v.includes('each: true'))) {
        validators.push('@IsString({ each: true })');
        validatorImports.add('IsString');
      }
    }

    /* ---------- ENUM ---------- */
    let swagger = mapped.swagger;

    if (field.enumType) {
      const options = [`enum: ${field.enumType}`, `enumName: '${field.enumType}'`];
      swagger = isRequired
        ? `@ApiProperty({ ${options.join(', ')} })`
        : `@ApiPropertyOptional({ ${options.join(', ')} })`;

      // ✅ avoid duplicate
      if (!validators.some((v) => v.includes('@IsEnum'))) {
        validators.push(`@IsEnum(${field.enumType}${field.isArray ? ', { each: true }' : ''})`);
      }

      validatorImports.add('IsEnum');

      const enumPath = field.enumPath || field.enumImport?.path;
      if (enumPath) {
        enumImportsMap.set(field.enumType, enumPath);
      }
    }

    /* ---------- TYPE FIX ---------- */
    let dtoType = mapped.dtoType || field.tsType;

    if (field.isArray && dtoType.endsWith('[]')) {
      dtoType = dtoType.replace(/\[\]$/, '');
    }

    /* ---------- EMBEDDED ---------- */
    if (field.embeddedSchema) {
      const nested = `${field.embeddedSchema.name}Dto`;

      dtoType = field.isArray ? `${nested}[]` : nested;

      swagger = isRequired
        ? `@ApiProperty({ type: () => ${field.isArray ? `[${nested}]` : nested} })`
        : `@ApiPropertyOptional({ type: () => ${field.isArray ? `[${nested}]` : nested} })`;

      validatorImports.add('ValidateNested');
      transformerImports.add('Type');

      // ✅ CLEAN OLD DECORATORS
      validators = validators.filter((v) => !v.includes('@ValidateNested') && !v.includes('@Type'));

      validators.push(field.isArray ? '@ValidateNested({ each: true })' : '@ValidateNested()');

      validators.push(`@Type(() => ${nested})`);
    } else if (field.isArray) {
      dtoType += '[]';
    }

    console.log(swagger);
    /* ---------- OUTPUT ---------- */
    body += `  ${swagger}\n`;

    [...new Set(validators.filter(Boolean))].forEach((v) => {
      body += `  ${v}\n`;
    });

    body += `  ${field.name}${isRequired ? '!' : '?'}: ${dtoType};\n\n`;
  }

  /* ======================================================
   * IMPORTS
   * ====================================================== */
  let imports = `import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';\n`;

  if (validatorImports.size) {
    imports += `import { ${[...validatorImports].join(', ')} } from 'class-validator';\n`;
  }

  if (transformerImports.size) {
    imports += `import { ${[...transformerImports].join(', ')} } from 'class-transformer';\n`;
  }

  if (enumImportsMap.size) {
    enumImportsMap.forEach((path, enumName) => {
      imports += `import { ${enumName} } from '${path}';\n`;
    });
  }

  /* ======================================================
   * FINAL
   * ====================================================== */
  return `
${imports}

${nestedDtoClasses.join('\n')}

export class Create${Entity}Dto {
${body}}
`;
};
