module.exports = ({ Entity, dtoFields, classComment }) => {
  // ✅ system fields
  const SYSTEM_FIELDS = ['_id', 'id', 'createdAt', 'updatedAt', 'deletedAt'];

  // ✅ auto-generated fields
  const autoGeneratedFields = (dtoFields?.create || [])
    .filter((f) => f.isAutoGenerated)
    .map((f) => f.name);

  // ✅ merge + unique
  const omitFields = [...new Set([...SYSTEM_FIELDS, ...autoGeneratedFields])];

  const omitFieldsString = omitFields.map((f) => `'${f}'`).join(', ');

  return `
import { PartialType, OmitType } from '@nestjs/swagger';
import { Create${Entity}Dto } from './create-${Entity.replace(
    /([a-z])([A-Z])/g,
    '$1-$2',
  ).toLowerCase()}.dto';

/**
 * Update${Entity}Dto
 * =================
 * ${classComment || `DTO for updating ${Entity}`}
 */
export class Update${Entity}Dto extends PartialType(
  OmitType(Create${Entity}Dto, [] as const),
) {}
`;
};
