module.exports = ({ Entity, ENTITY, entity, fields }) => {
  // Detect unique fields
  const uniqueFields = fields.filter((f) => f.isUnique && f.source === 'user');
  const uniqueFieldNames = uniqueFields.map((f) => f.name);
  const hasUniqueFields = uniqueFields.length > 0;
  const hasName = uniqueFields.some((f) => f.name === 'name');

  // Detect reference fields (like countryId)
  const referenceFields = fields.filter(
    (f) => f.refType && f.source === 'user',
  );
  const hasReferenceFields = referenceFields.length > 0;

  // Detect system-generated ID fields
  const systemIdFields = fields.filter(
    (f) => f.isIdField && (f.isSystemGenerated || f.hasAutoGeneratedDecorator),
  );
  const systemIdFieldNames = systemIdFields.map((f) => f.name);

  // Get the main business ID field (like countryId, vanId, etc.)
  const businessIdField = fields.find(
    (f) =>
      f.name.endsWith('Id') &&
      !f.name.startsWith('_') &&
      f.name !== 'id' &&
      (f.isRequired || f.isUnique),
  );
  const businessIdFieldName = businessIdField
    ? businessIdField.name
    : `${entity}Id`;

  // Check if we need text normalization
  const needsTextNormalization = fields.some(
    (f) => f.name === 'name' && f.tsType === 'string' && f.source === 'user',
  );

  return `
/**
 * ${Entity} Service
 * ${'-'.repeat(Entity.length + 9)}
 * Purpose : Handles business logic for ${entity} lifecycle management
 * Used by : ${Entity}Controller
 *
 * Responsibilities:
 * - Create ${entity}s
 * - Restore soft-deleted ${entity}s
 * - Fetch ${entity} lists with filters and pagination
 * - Retrieve single ${entity} details
 * - Update ${entity} information
 * - Soft-delete ${entity}s
 *
 * Notes:
 * - All write operations are transaction-safe
 * ${hasUniqueFields ? `- Unique field constraints are enforced${hasReferenceFields ? ' with reference validation' : ''}` : ''}
 * - Soft deletes preserve audit history
 */

import {
  Injectable,
  NotFoundException,
  ConflictException,
  BadRequestException,
  HttpStatus,
} from '@nestjs/common';

import { MongoService } from 'src/core/database/mongo/mongo.service';
import { MongoRepository } from 'src/core/database/mongo/mongo.repository';
import { FilterQuery } from 'src/core/database/mongo/mongo.interface';

import { ${Entity}, ${Entity}Schema } from 'src/core/database/mongo/schema/${entity}.schema';

import { ${ENTITY} } from './${entity}.constants';
import { Create${Entity}Dto } from './dto/create-${entity}.dto';
import { Update${Entity}Dto } from './dto/update-${entity}.dto';
import { ${Entity}QueryDto } from './dto/${entity}-query.dto';
import { IdGenerator } from 'src/shared/utils/id-generator.utils';
${
  needsTextNormalization
    ? `import { TextNormalizer } from 'src/shared/utils/text-normalizer.utils';
import { NormalizeType } from 'src/shared/enums/normalize.enums';`
    : ''
}

@Injectable()
export class ${Entity}Service extends MongoRepository<${Entity}> {
  constructor(mongo: MongoService) {
    super(mongo.getModel(${Entity}.name, ${Entity}Schema));
  }

  /**
   * Create ${Entity}
   * ${'-'.repeat(Entity.length + 7)}
   * Purpose : Create new ${entity} or restore soft-deleted ${entity}
   */
  async create(payload: Create${Entity}Dto) {
    return this.withTransaction(async (session) => {
      ${
        needsTextNormalization
          ? `// Normalize name if provided
      if (payload.name) {
        payload.name = TextNormalizer.normalize(payload.name, NormalizeType.TITLE);
      }`
          : ''
      }

      // Check for existing record (including soft-deleted)
      const filter: FilterQuery<${Entity}> = {};

      ${
        hasUniqueFields
          ? uniqueFields
              .map((field) => {
                const fieldName = field.name;
                return `if (payload.${fieldName}) {
          filter.${fieldName} = payload.${fieldName};
        }`;
              })
              .join('\n      ')
          : ''
      }

      ${
        hasReferenceFields
          ? referenceFields
              .map((field) => {
                const fieldName = field.name;
                return `// Reference field validation for ${fieldName}
      if (payload.${fieldName}) {
        // TODO: Add reference validation for ${field.refType}
        // You might want to check if the referenced entity exists
      }`;
              })
              .join('\n      ')
          : ''
      }

      const existing = await this.findOne(
        filter,
        { session, includeDeleted: true },
      );

      // If exists and not deleted, throw conflict
      if (existing && !existing.isDeleted) {
        throw new ConflictException(${ENTITY}.DUPLICATE);
      }

      // Restore soft-deleted record
      if (existing?.isDeleted) {
        await this.updateById(
          existing._id.toString(),
          {
            ...payload,
            status: 'ACTIVE',
            isDeleted: false,
          },
          { session },
        );

        return {
          statusCode: HttpStatus.OK,
          message: ${ENTITY}.CREATED,
          data: { ${businessIdFieldName}: existing.${businessIdFieldName} },
        };
      }

      // Create new record with system-generated ID
      const doc = await this.save(
        {
          ${businessIdFieldName}: IdGenerator.generate('${ENTITY.slice(0, 4)}', 8),
          ...payload,
        },
        { session },
      );

      return {
        statusCode: HttpStatus.CREATED,
        message: ${ENTITY}.CREATED,
        data: doc,
      };
    });
  }

  /**
   * Get ${Entity}s (List)
   * ${'-'.repeat(Entity.length + 10)}
   */
  async findAll(query: ${Entity}QueryDto) {
    const { searchText, status, page = 1, limit = 20${hasReferenceFields ? referenceFields.map((f) => `, ${f.name}`).join('') : ''} } = query;

    const filter: FilterQuery<${Entity}> = {};

    if (status) filter.status = status;
    ${
      hasReferenceFields
        ? referenceFields
            .map((f) => {
              return `if (${f.name}) filter.${f.name} = ${f.name};`;
            })
            .join('\n    ')
        : ''
    }

    if (searchText) {
      const regex = new RegExp(searchText, 'i');
      filter.$or = [
        { ${businessIdFieldName}: regex },
        ${fields
          .filter((f) => f.tsType === 'string' && f.source === 'user')
          .map((f) => {
            return `{ ${f.name}: regex }`;
          })
          .join(',\n        ')}
      ].filter(Boolean);
    }

    const result = await this.paginate(filter, {
      page,
      limit,
      sort: { createdAt: -1 },
      lean: true,
    });

    return {
      statusCode: HttpStatus.OK,
      message: ${ENTITY}.FETCHED,
      data: result.items,
      meta: result.meta,
    };
  }

  /**
   * Get ${Entity} by ${businessIdFieldName}
   * ${'-'.repeat(businessIdFieldName.length + Entity.length + 12)}
   */
  async findBy${businessIdFieldName.charAt(0).toUpperCase() + businessIdFieldName.slice(1)}(${businessIdFieldName}: string) {
    const doc = await this.findOne({ ${businessIdFieldName} }, { lean: true });

    if (!doc) throw new NotFoundException(${ENTITY}.NOT_FOUND);

    return {
      statusCode: HttpStatus.OK,
      message: ${ENTITY}.FETCHED,
      data: doc,
    };
  }

  /**
   * Update ${Entity}
   * ${'-'.repeat(Entity.length + 8)}
   */
async update(${businessIdFieldName}: string, dto: Update${Entity}Dto) {
  return this.withTransaction(async (session) => {
    ${
      needsTextNormalization
        ? `// Normalize name if provided in update
    if (dto.name) {
      dto.name = TextNormalizer.normalize(dto.name, NormalizeType.TITLE);
    }`
        : ''
    }

    ${
      hasUniqueFields
        ? `// Check for unique field conflicts on update
    ${uniqueFields
      .map((field) => {
        const fieldName = field.name;
        return `if (dto.${fieldName}) {
        const existing = await this.findOne(
          {
            ${fieldName}: dto.${fieldName},
            ${businessIdFieldName}: { $ne: ${businessIdFieldName} }
          } as unknown as FilterQuery<${Entity}>,
          { session },
        );

        if (existing) {
          throw new ConflictException(${ENTITY}.DUPLICATE);
        }
      }`;
      })
      .join('\n      ')}`
        : ''
    }

    const doc = await this.updateOne(
      { ${businessIdFieldName} },
      dto,
      { session, new: true },
    );

    if (!doc) throw new NotFoundException(${ENTITY}.NOT_FOUND);

    return {
      statusCode: HttpStatus.OK,
      message: ${ENTITY}.UPDATED,
      data: doc,
    };
  });
}

  /**
   * Delete ${Entity} (Soft Delete)
   * ${'-'.repeat(Entity.length + 15)}
   */
  async delete(${businessIdFieldName}: string) {
    const deleted = await this.withTransaction(async (session) => {
      const existing = await this.findOne(
        { ${businessIdFieldName}, isDeleted: false },
        { session },
      );

      if (!existing) throw new NotFoundException(${ENTITY}.NOT_FOUND);

      await this.softDelete({ ${businessIdFieldName} }, { session });

      return existing;
    });

    return {
      statusCode: HttpStatus.OK,
      message: ${ENTITY}.DELETED,
      data: deleted,
    };
  }

  /**
   * Handle database duplicate key errors
   */
  private handleDuplicateError(error: any): never {
    // Check if it's a MongoDB duplicate key error
    if (error.code === 11000 || error.code === 11001) {
      const fieldMatch = error.message.match(/index:\\s*([^\s]+)/);
      const fieldName = fieldMatch ? fieldMatch[1].split('_')[0] : 'unknown';
      
      throw new ConflictException(
        \`$\{${ENTITY}.DUPLICATE\} (\${fieldName})\`
      );
    }
    throw error;
  }
}
`;
};
