/* ---------------- ENUM CONSTANTS ---------------- */

export const MEDIA_TYPE = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
  AUDIO: 'AUDIO',
  OTHER: 'OTHER',
} as const;

export const MEDIA_OWNER_TYPE = {
  PRODUCT: 'PRODUCT',
  VARIANT: 'VARIANT',
  CUSTOMER: 'CUSTOMER',
  EMPLOYEE: 'EMPLOYEE',
  ORDER: 'ORDER',
  PAYMENT: 'PAYMENT',
  VISIT: 'VISIT',
  INVENTORY: 'INVENTORY',
  ROUTE: 'ROUTE',
  WAREHOUSE: 'WAREHOUSE',
  GENERAL: 'GENERAL',
  CATEGORY: 'CATEGORY',
} as const;

export const MEDIA_PURPOSE = {
  MAIN: 'MAIN',
  GALLERY: 'GALLERY',
  THUMBNAIL: 'THUMBNAIL',
  PROFILE: 'PROFILE',
  COVER: 'COVER',
  DOCUMENT: 'DOCUMENT',
  RECEIPT: 'RECEIPT',
  SIGNATURE: 'SIGNATURE',
  PROOF: 'PROOF',
  OTHER: 'OTHER',
} as const;
