export const PERMISSIONS = {
  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  CUSTOMER_CREATE: 'CUSTOMER_CREATE',
  CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
  CUSTOMER_DELETE: 'CUSTOMER_DELETE',

  EMPLOYEE_VIEW: 'EMPLOYEE_VIEW',
  EMPLOYEE_CREATE: 'EMPLOYEE_CREATE',
  EMPLOYEE_UPDATE: 'EMPLOYEE_UPDATE',
  EMPLOYEE_DELETE: 'EMPLOYEE_DELETE',

  ORDER_VIEW: 'ORDER_VIEW',
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_UPDATE: 'ORDER_UPDATE',
  ORDER_DELETE: 'ORDER_DELETE',

  ADDRESS_VIEW: 'ADDRESS_VIEW',
  ADDRESS_CREATE: 'ADDRESS_CREATE',
  ADDRESS_UPDATE: 'ADDRESS_UPDATE',
  ADDRESS_DELETE: 'ADDRESS_DELETE',

  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',

  PRODUCT_VARIATNT_VIEW: 'PRODUCT_VARIATNT_VIEW',
  PRODUCT_VARIATNT_CREATE: 'PRODUCT_VARIATNT_CREATE',
  PRODUCT_VARIATNT_UPDATE: 'PRODUCT_VARIATNT_UPDATE',
  PRODUCT_VARIATNT_DELETE: 'PRODUCT_VARIATNT_DELETE',

  OFFER_VIEW: 'OFFER_VIEW',
  OFFER_CREATE: 'OFFER_CREATE',
  OFFER_UPDATE: 'OFFER_UPDATE',
  OFFER_DELETE: 'OFFER_DELETE',

  CATEGORY_VIEW: 'CATEGORY_VIEW',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',

  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_COLLECT: 'PAYMENT_COLLECT',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
