// src/shared/decorators/auto-generated.decorator.ts
import { applyDecorators } from '@nestjs/common';
import { Prop } from '@nestjs/mongoose';

export function AutoGenerated() {
  return applyDecorators(
    Prop({ 
      required: true,
      // Add any other default mongoose options
    })
  );
}

export function SystemField() {
  return applyDecorators(
    Prop({
      required: true,
      // Mark as system field
    })
  );
}

export function UserInput() {
  return applyDecorators(
    Prop()
    // Fields without special decorator are user input by default
  );
}