const fs = require('fs');
const path = require('path');

exports.parseSchema = (ROOT, entity) => {
  /* ======================================================
   * NAMING HELPERS
   * ====================================================== */
  const toPascalCase = (str) =>
    str
      .split('-')
      .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
      .join('');

  const toConstantCase = (str) => str.replace(/-/g, '_').toUpperCase();

  const toCamelCase = (str) =>
    str
      .split('-')
      .map((s, i) => (i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1)))
      .join('');

  const camelEntity = toCamelCase(entity);
  const Entity = toPascalCase(entity);
  const ENTITY = toConstantCase(entity);

  /* ======================================================
   * LOAD SCHEMA
   * ====================================================== */
  const schemaPath = path.join(
    process.cwd(),
    'src/core/database/mongo/schema',
    `${entity}.schema.ts`,
  );

  if (!fs.existsSync(schemaPath)) {
    throw new Error(`Schema not found: ${schemaPath}`);
  }

  const schema = fs.readFileSync(schemaPath, 'utf8');

  /* ======================================================
   * IMPORT PARSING
   * ====================================================== */
  const imports = {
    enums: new Map(),
  };

  const importRegex = /import\s*{([^}]+)}\s*from\s*['"]([^'"]+)['"]/g;
  let match;

  while ((match = importRegex.exec(schema)) !== null) {
    const items = match[1].split(',').map((i) => i.trim());
    const importPath = match[2];

    items.forEach((item) => {
      const info = {
        name: item,
        path: importPath,
        statement: `import { ${item} } from '${importPath}';`,
      };

      if (importPath.includes('/enums/')) {
        imports.enums.set(item, info);
      }
    });
  }

  /* ======================================================
   * EMBEDDED SCHEMA PARSING
   * ====================================================== */
  const embeddedSchemas = new Map();

  const embeddedSchemaRegex = /export\s+class\s+(\w+)\s*{([\s\S]*?)^}/gm;
  let embeddedMatch;

  while ((embeddedMatch = embeddedSchemaRegex.exec(schema)) !== null) {
    const className = embeddedMatch[1];

    if (className === Entity) continue;

    const body = embeddedMatch[2];
    const fields = [];

    const fieldRegex =
      /((?:@\w+\([^\)]*\)\s*)*)@Prop\(([\s\S]*?)\)\s*(\w+)\s*(\??|!?)\s*:\s*([^;\n]+);/g;

    let fieldMatch;

    while ((fieldMatch = fieldRegex.exec(body)) !== null) {
      const rawType = fieldMatch[5].trim();

      fields.push({
        name: fieldMatch[3],
        tsType: rawType,
        isArray: rawType.endsWith('[]') || rawType.includes('Array<'),
      });
    }

    embeddedSchemas.set(className, {
      name: className,
      fields,
    });
  }

  /* ======================================================
   * MAIN SCHEMA EXTRACTION
   * ====================================================== */
  const mainSchemaRegex = new RegExp(`export\\s+class\\s+${Entity}\\s*{([\\s\\S]*?)^}`, 'm');

  const mainSchemaMatch = schema.match(mainSchemaRegex);

  if (!mainSchemaMatch) {
    throw new Error(`Schema not found: ${Entity}`);
  }

  const mainSchemaBody = mainSchemaMatch[1];

  /* ======================================================
   * FIELD PARSING
   * ====================================================== */
  const fields = [];

  const fieldRegex =
    /((?:@\w+\([^\)]*\)\s*)*)@Prop\(([\s\S]*?)\)\s*(\w+)\s*(\??|!?)\s*:\s*([^;\n]+);/g;

  let fieldMatch;

  while ((fieldMatch = fieldRegex.exec(mainSchemaBody)) !== null) {
    const decorators = fieldMatch[1] || '';
    const propContent = fieldMatch[2];
    const fieldName = fieldMatch[3];
    const optionalMark = fieldMatch[4] || '';
    const rawType = fieldMatch[5].trim();

    const isArray = rawType.endsWith('[]') || rawType.includes('Array<');

    const isRequired = propContent.includes('required: true');

    const isAutoGenerated = decorators.includes('@AutoGenerated');

    /* ---------- ENUM ---------- */
    let enumType = null;
    let enumImport = null;

    const enumMatch = propContent.match(/enum:\s*(\w+)/);

    if (enumMatch) {
      enumType = enumMatch[1];

      if (imports.enums.has(enumType)) {
        enumImport = imports.enums.get(enumType);
      }
    }

    /* ---------- EMBEDDED ---------- */
    let embeddedSchema = null;

    if (embeddedSchemas.has(rawType)) {
      embeddedSchema = embeddedSchemas.get(rawType);
    }

    const embeddedMatch = propContent.match(/type:\s*(\w+)Schema/);

    if (embeddedMatch) {
      const name = embeddedMatch[1];
      if (embeddedSchemas.has(name)) {
        embeddedSchema = embeddedSchemas.get(name);
      }
    }

    /* ---------- FIELD OBJECT ---------- */
    fields.push({
      name: fieldName,
      tsType: rawType,

      isArray,
      isRequired,
      isOptional: !isRequired,

      isAutoGenerated, // 🔥 important

      enumType,
      enumImport,
      enumPath: enumImport?.path,

      embeddedSchema,

      source: 'user',
      dtoInclude: ['create', 'update', 'response', 'query'],
    });
  }

  /* ======================================================
   * ENUM IMPORT COLLECTION
   * ====================================================== */
  const uniqueEnumImports = new Set();

  fields.forEach((field) => {
    if (field.enumImport) {
      uniqueEnumImports.add(field.enumImport.statement);
    }

    if (!field.enumPath && field.enumImport?.path) {
      field.enumPath = field.enumImport.path;
    }
  });

  const queryFields = fields.filter(
    (f) =>
      !f.isAutoGenerated && !f.embeddedSchema && f.name !== 'createdAt' && f.name !== 'updatedAt',
  );

  const dtoFields = {
    create: fields,
    update: fields,
    response: fields,
    query: queryFields,
  };

  /* ======================================================
   * RETURN
   * ====================================================== */
  return {
    entity,
    Entity,
    ENTITY,
    camelEntity,

    fields,
    dtoFields,

    embeddedSchemas: Array.from(embeddedSchemas.values()),

    enumImports: Array.from(uniqueEnumImports),

    moduleDir: path.join(ROOT, 'src/modules/v1', entity),
    dtoDir: path.join(ROOT, 'src/modules/v1', entity, 'dto'),

    rawSchema: schema,
  };
};
