export enum VanStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BREAKDOWN = 'BREAKDOWN',
}

export enum VanBreakdownReason {
  ENGINE_ISSUE = 'ENGINE_ISSUE',
  TYRE_PUNCTURE = 'TYRE_PUNCTURE',
  ACCIDENT_DAMAGE = 'ACCIDENT_DAMAGE',
  ELECTRICAL_ISSUE = 'ELECTRICAL_ISSUE',
  MAINTENANCE_SERVICE = 'MAINTENANCE_SERVICE',
  OTHER = 'OTHER',
}
